<div id="search" class="searchOrgs">
    <?php
    if($this->results){?>
    <?php	
    	echo $this->results;
     } else { 
     ?>
	<form method="POST">
    	<div id="searchTabs"><img src="/images/search/tabs/01.gif" /><a href="/search"><img src="/images/search/tabs/02.gif" /></a><img src="/images/search/tabs/03.gif" /><img src="/images/search/tabs/04.gif" /></div>
    	<div id="searchTownsImgs" >
    		<img src="/images/search/org/towns_1.gif"  />
            <div>
                <div class="townName first">
                    <input type="checkbox" name="" value="" id="" class="regcbx_all" CHECKED/>All Areas
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_1" value="" id="chkbx_region_1" class="regcbx" />
                    Marlboro /
                    <br/>
                    Colts Neck
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_2" value="" id="chkbx_region_2"  class="regcbx"/>Manalapan
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_3" value="" id="chkbx_region_3"  class="regcbx"/>Freehold
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_4" value="" id="chkbx_region_4"  class="regcbx"/>
                    Howell /
                    <br/>
                    Farmingdale
                </div>
            </div>
    		<img src="/images/search/org/areas_2.gif" />
            <div>
                <div class="townName first">
                    <input type="checkbox" name="chkbx_region_5" value="" id="chkbx_region_5" class="regcbx" />
                    Aberdeen - Matawan /
                    <br/>
                    Hazlet
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_6" value="" id="chkbx_region_6" class="regcbx" />
                    Holmdell /
                    <br/>
                    Middletown
                </div>
                <div class="townName">
                    <input type="checkbox" name="chkbx_region_7" value="" id="chkbx_region_7" class="regcbx" />
                    RedBank /
                    <br/>
                    Eatontown
                </div>
            </div>
    		<!--<img src="/images/search/area_names2.gif" />-->
    	</div>
        
    	<?php
    	   echo $this->towns;
		?>
                
		<div id="zip">
			<h5><span class="lwr">or</span> Zip Code</h5>
			<div id="searchZip"><input type="text" name="zip" /></div>
		</div>
    		
    	<?php
    	   echo $this->cats;
    	?>
        
		<div id="keywords">
			<h5><span class="lwr">by</span> keyword</h5>
			<div id="searchKey">
				<input type="text" name="keyword" id="keyword" />
				<div><i>eg: women, children, drugs</i></div>
			</div>	
		</div>
        
		<div id="searchSubmit">
		  <input type="submit" class="submit" />
		</div>
	</form>
    <?php } ?>
</div>