<?php //echo $this->album_array; ?>
<style>
div#videogallery_carousel_wrapper div.albumhead {
	background:#006699;
	color:white;
	font-size:10pt;
	padding:3px;
	margin-top:.5em;
}
div.videotoggle {
	width:50px;
	color:white;
	background-color:#0678BF;
	border:1px solid white;
	float:left;
	padding:2px;
	text-align:center;
	cursor:pointer;
}

</style>
<script>
showVideo = function(video) {
	$('videoPlayer').innerHTML = '<object type="application/x-shockwave-flash" style="width:425px; height:350px;z-index:0" data="http://www.youtube.com/v/' + video + '"><param name="movie" value="http://www.youtube.com/v/' + video + '" /><param name="wmode" value="transparent" /></object> ';
}
</script>

 <div id="videogallery">
    <div id="videogallery_upload">
    	<div id="videogallery_carousel_wrapper">
    	<div id="r" >
    	<div id="videoToggleWrapper" >
    	<?php foreach($this->albums as $k=>$album){	
    		$id = ($album->getId() == 'default') ? '0' : $album->getId();
    		$name = ($album->getId() == 'default') ? 'videos' : $album->getname();
    		?> 
    			<div onclick="FM.VideoGallery.toggleOn(<?php echo $id ?>)" class="tab videotoggle"  id="videotoggle_<?php echo $id ?>" onMouseOver="toolTip('<?php echo $name; ?>', 150)" onMouseOut="toolTip()" ><?php echo substr($name, 0 , 6); ?></div>
    		<? } ?>
    		</div>
    		<div class="clear" style="border-top:1px solid green;padding-bottom:3px;">&nbsp;</div>
		<div style="width:160px;float:left;max-height:360px;overflow-y:auto;overflow-x:hidden;" id='videoScrollers' >
			
    	<?php foreach($this->albums as $k=>$album){	
    		$id = ($album->getId() == 'default') ? '0' : $album->getId();
    		$show = ($album->getId() == 'default') ? 'inline' : 'none';
    		?> 
               		<div style="width:150px;display:<?= $show ?>" id="videoalbumscroll_<?php echo $id ?>" >
               		<div id="videoalbum_<?php echo $album->getId() ?>" <?php echo ($album->getName() == '' && !$this->default) ? 'style=""'  : ''; ?>>
               			<div class="albumhead" ><?php echo ($album->getName() != '') ? $album->getName() : 'Videos';?>&nbsp;<?php if($album->getDescription()){ ?>&nbsp;<img src="/images/icons/info-icon.png" onMouseOver="toolTip('<?php echo $album->getDescription(); ?>', 150)" onMouseOut="toolTip()" /><?php } ?><?php if($this->admin && $album->getName() != '') { ?><span style="float:right"><img src="/images/icons/remove.png" onclick="FM.VideoGallery.removeAlbum('<?php echo $album->getId() ?>', '<?php echo ($album->getName() != '') ? $album->getName() : 'Default';?>')" /></span><?php } ?></div>
               		</div>
               		<?php  
    		$images = $album->getImages();
    		foreach ($images as $i=>$thumb) {
    			$match = explode('v=', $thumb['video']);
    			$match = explode('&', $match[1]);
    			$video = $match[0]; ?>
    			
    			<div style="margin:0px auto;" id="videoThumbWrapper_<?=$thumb['id']; ?>">
    				<?php if($this->admin) { ?> <div><span style="float:right"><img src="/images/icons/remove.png" onclick="FM.VideoGallery.removeVideo('<?php echo $thumb['id'] ?>')"/></span></div> <?php } ?>
    				<div><?= $thumb['description'] ?></div>
					<img src = "http://img.youtube.com/vi/<?= $video?>/default.jpg" onclick="showVideo('<?= $video?>')" />
				</div>
				
    			<?
    		} ?>
    		</div>
    		<?php
    		
    		//if($album->getName() != ''){
    		//echo ($album->getName() != '') ? $album->getName() : 'Default';
               		
               		//	}
    	}?>
    	</div>
    	<div id="videoPlayer" style="width:425px;float:right;height:350px;background:url(/images/bgds/photogallery.gif) repeat;">
               			
    				</div>
               	
    		</div>	
 <div class="clear">&nbsp;</div> 
 <?php if($this->admin) {?><div id='newutube' style="margin:.5em;margin-top:.1em;cursor:pointer;text-align:right;font-size:10pt;text-transform:capitalize;color:green;" onclick='jQuery("#newutube").colorbox({
			href : "http://www.youtube.com/create_account",
			width:"1100px",
			height : "800px",
			iframe : true,
			opacity : .4
		});'>click <span style="color:blue;text-decoration:underline">here</span> to upload a new youtube video</div><? } ?>
 <?php if($this->admin) { ?> 
 <div id="galleryadmin">
 	<!--<div>
 		<input type ="checkbox" onclick="FM.PhotoGallery.toggleAlbumOn(this);" <? echo (!$this->default) ? ' checked ' : ''; ?>/>&nbsp;<label><strong>Show Albums Only</strong></label><br />
       		<i>(When selected uncategorized images will not be shown in the default 'pictures' album)</i>
       	</div>
       	-->
       <form class="zend_form">
     
 	      <div style="clear:both;">
 	       
               <label>Add a video to</label>
               <select id="videoAlbumselect">
               	<option value='0'>Videos
               	<?php foreach($this->albums as $k=>$album){
               		if($album->getId() != '' && $album->getName() != '') {?>  
               			<option value='<?php echo $album->getId(); ?>'><?php echo $album->getName(); ?></option>
               		<?php } 
               	}?>
}
               </select>
           </div>
           <div>
               <label>YouTube Link : </label><input type="text" id="videoVideo" />
           </div>  
           <div>
               <label>description</label><textarea id="videoDescription" name="tagline"></textarea>
           </div>          
			 <input type="submit" class="submit" value="add video" onclick="FM.VideoGallery.addVideo();return false;" />               
       </form>	
       
       <h2>Add an album</h2>
        <form class="zend_form">
        <div>
               <label>name</label><input type="text" id="videoAlbumname" name="albumname" />
           </div>  
           <div>
               <label>description</label><textarea id="videoAlbumdesc" name="albumdesc"></textarea>
           </div>                  
            <input type="submit" class="submit" value="add album" onclick="FM.VideoGallery.addAlbum();return false;" />      
       </form>	
</div>

<? }?>
 	</div>    
</div>
</div>
<?php if($this->admin) { ?>  
<style>
	.crusade .col1 div#content #media #videogallery #videogallery_upload #videogallery_carousel .jcarousel-list li,
            .crusade .col1 div#content #media #videogallery #videogallery_upload #videogallery_carousel .jcarousel-item {
	height:90px;
            }
            
     .crusade .col1 div#content #media #videogallery #videogallery_upload #videogallery_carousel .jcarousel-list li,
         .crusade .col1 div#content #media #videogallery div#galleryadmin {
		margin-top:.5em;
		padding:.5em;
		border:1px solid black;
}
</style>
<?php } ?>