<?php 
	foreach ($this->banners as $banner) { 	?>
	<?php $template = $banner->get('template');?> 
	
	<div class="banner <?php echo $template['class']; ?>">
	<?php
		if($template['logo'] == 1) {?>
		<div class="imgWrap">
			<a href="http://<?php echo $banner->get('url'); ?>">
				<img src="<?php echo $banner->get('path') . '/' . $banner->get('medianame'); ?>"   />
			</a>
		</div>
	<?php } ?>
	<?php
		if($template['headline'] == 1) {
			echo "<h1>{$banner->get('headline')}</h1>";
		}
		?>
		<div class="copy">
			<?php echo $banner->get('copy'); ?>
		</div>
	</div>
<?php 	}
?>