<div id="coupons">
<?php	foreach($this->coupons as $index=>$obj){
	switch($obj->getType()) {
		case 1:
			print $this->partial('tabs/couponoptions/coupon1.phtml', array(
			'obj'=>$obj));
			break;
		case 2:
			print $this->partial('tabs/couponoptions/coupon2.phtml', array(
			'obj'=>$obj));
			break;
		case 3:
			print $this->partial('tabs/couponoptions/coupon3.phtml', array(
			'obj'=>$obj));
			break;
			break;
		case 4:
			print $this->partial('tabs/couponoptions/coupon4.phtml', array(
			'obj'=>$obj));
			break;
			break;
	}
}
?>
</div>