<div style="display:none">
The mission of 4Monmouth is to empower and engage people in Monmouth County to collect free information on local non-profit organizations as well as develop good, mutually advantageous relationships with local businesses.
4Monmouth was created to provide useful information to the public and to facilitate dialogue between local organizations and its members.
4Monmouth’s goal is to provide people with a true, tangible value to make important decisions such as:
    Patronizing a business
    How to save money on every day purchases as well as on large projects
    Seeking help from a local organization
    Learning about local organizations
    Learning about local religious organizations
    Volunteering
    Being in touch with your community.
Together with a network of organizations, 4Monmouth provides the essential infrastructure and an organizational framework for the support and development of an effective collaboration which serves this mission.
</div>
<div id="rssContainer">
	<?php 
    echo $this->monmouthnews;
    echo $this->calendarrss;
    echo $this->topstories;
    echo $this->financenews;
    echo $this->entertainmentnews;
    echo $this->sportsnews;
    //echo $this->financenews;
    //echo $this->entertainment; 
    ?>
</div>