<div class="subpage" id="user">
    <h4>Retrieve Your Password</h4>
    <div class="content">
    	<a class="login" href="/account">Login</a>		
    	<?php if($this->failed){?>
    	<div id="mstatusMessage" style="color:red;font-size:11pt;">No member was found with the email  <?php echo $this->email; ?>.</div>
    	<?php } ?>
    	<?php if($this->sent){?>		
    	<div id="mstatusMessage">An email has been sent to <?php echo $this->email; ?> with your password.</div>
    	<?php } else {?>
    	<div id="forgotten">
    		<div>Please enter the email attached to your account and we will send you your password :</div>
    		<form method="POST">
    			<input class="email" type="text" name="email" />
    			<input id="submit" type="submit" value="submit">
    		</form>	
    	</div>
    	<?php } ?>
    </div>
</div>