<h4>My Information</h4>
<div class="content">
	<a class="logout" href="/access/logout" >Logout</a>
	<div id="statusMessage"></div>
	<ul id="memberInfo">
		<li><label>Username:</label><span class="exempt"><?php echo $this->member->get('uname'); ?></span></li>
		<li><label>First Name:</label><span class="caps"><?php echo $this->member->get('firstname'); ?></span></li>
		<li><label>Middle:</label><span class="caps"><?php echo $this->member->get('middlename'); ?></span></li>
		<li><label>Last Name:</label><span class="caps"><?php echo $this->member->get('lastname'); ?></span></li>
		<li><label>Address 1:</label><span><?php echo $this->member->get('address1'); ?></span></li>
		<?php if($this->member->get('address2') != '') { ?>
		<li><label>Address 2:</label><span><?php echo $this->member->get('address2'); ?></span></li>
		<?php } ?>
		<li><label>City:</label><span class="caps"><?php echo $this->member->get('city'); ?></span></li>
		<li><label>State:</label><span class="exempt caps"><?php echo $this->member->get('state'); ?></span></li>
		<li><label>Zip:</label><span><?php echo $this->member->get('zip'); ?></span></li>
		<li><label>Email:</label><span><?php echo $this->member->get('email'); ?></span></li>
		<li><label>Phone:</label><span><?php echo $this->member->get('phone'); ?></span></li>
	</ul>		
	<a class="edit" id="editBtn" onclick="FM.Account.edit()">edit</a>
</div>

<h4>Change Your Password</h4>
 <div class="content">
	<ul id="passwordInfo">
		<li><label>Old Password : </label> <input type="password" id="oldPwdConf" /></li>
		<li><label>New Password : </label> <input type="password" id="newPwd" /></li>
		<li><label>Confirm : </label> <input type="password" id="newPwdConf" /></li>
	</ul>	
	<a class="update" id="updateBtn" onclick="FM.Account.updatePassword(<?php echo $this->member->get('uid'); ?>)">update</a>
</div>

<h4>My Memberships</h4>
 <div class="content">
 	<div class="memberships">
 		<?php if($this->member->isRoot()) { ?>
 			<div class="odd">Administration Panels
		                <a class="memberOrgLink" href="/root/admin">Go to Admin</a>
		            </div>
 		<?php }?>
 		<?php
			$count = 0;
			 foreach ($this->member->getOrgs() as $index=>$org) { 
			 	
				if($org->getname() != '') {
					$count++;
					$link = $org->getLink(); ?>
					<div class="<?php if($count%2) print 'odd'?>"><?php echo $org->getName() ?>
		                <a class="memberOrgLink"href="<?php echo $link ?>">view</a>
		            </div>
				<?php }
				} ?>
		</div>		
 </div>
