<div id="weatherWidget">
	<div class="inner">
	<!--
		<div id="wx_module_9328">
	        <a href="http://www.weather.com/weather/local/07701">Red Bank Weather Forecast, NJ (07701)</a>
	    </div>
	    <script type="text/javascript">
	        
	        /* Locations can be edited manually by updating 'wx_locID' below.  Please also update */
	        /* the location name and link in the above div (wx_module) to reflect any changes made. */
	        var wx_locID = '07701';
	        
	        /* If you are editing locations manually and are adding multiple modules to one page, each */
	        /* module must have a unique div id.  Please append a unique # to the div above, as well */
	        /* as the one referenced just below.  If you use the builder to create individual modules  */
	        /* you will not need to edit these parameters. */
	        var wx_targetDiv = 'wx_module_9328';
	        
	        /* Please do not change the configuration value [wx_config] manually - your module */
	        /* will no longer function if you do.  If at any time you wish to modify this */
	        /* configuration please use the graphical configuration tool found at */
	        /* https://registration.weather.com/ursa/wow/step2 */
	        var wx_config = 'SZ=180x150*WX=FHW*LNK=SSNL*UNT=F*BGC=ebebeb*MAP=null|null*DN=4monmouth.com*TIER=0*PID=1143445000*MD5=d34db3f7c6b37423055736c1e0a8b68e';
	        document.write('<scr' + 'ipt src="' + document.location.protocol + '//wow.weather.com/weather/wow/module/' + wx_locID + '?config=' + wx_config + '&proto=' + document.location.protocol + '&target=' + wx_targetDiv + '"></scr' + 'ipt>');
	    </script>
	    -->
	    <!-- AddThis Button BEGIN -->
<div style="text-align:center"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=ra-4e5e6f3e2d283d26">
<img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a></div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e5e6f3e2d283d26"></script>
<!-- AddThis Button END -->
	</div>

</div>
