		<div class="footerFineprint">
		    <div>
		       <!-- <a href="" onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://yoursite.com');return false;">Make This My Homepage</a>
		        | --><a href="/sitemap">Site Map</a>
		        | <a href="/legal">Legal Notice</a>
		        | <a href="/privacy">Privacy Policy</a>
		    </div>
		    <div>
		        &copy;2010 4Counties Inc, All Rights Reserved
		    </div>
		</div>
	</div>
	<div id="statusMessage">
		test
	</div>
</body>
</html>
