<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> Red Bank Restaurants | Freehold Tanning | 4Monmouth.com!</title>
<?php if($this->layout()->event instanceof FM_Components_Events ){ 
	$event = $this->layout()->event;
	?>
	 <meta property="og:title" content="<?= $event->getName(); ?>"/>
    <meta property="og:type" content="event"/>
    <meta property="og:url" content="http://4monmouth.com/utilities/viewevent/<?= $event->getEventId(); ?>"/>
    <meta property="og:site_name" content="4Monmouth"/>
    <meta property="og:image" content="http://4monmouth.com/images/socialmedia/4MLocal.jpg"/>
    <meta property="og:description"
          content="<?= $event->getDescription(); ?>."/>
 <? } else {?>
  <meta property="og:title" content="4 Monmouth,com"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="http://4monmouth.com/"/>
    <meta property="og:image" content="http://4monmouth.com/images/socialmedia/4M.jpg"/>
    <meta property="og:site_name" content="4Monmouth.com"/>
 <? } ?>
<meta name="keywords" content="momouth county" />
<meta name="description" content="Your Monmouth County, NJ source for Manalapan, Marlboro, Freehold, Hazlet and Red Bank Restaurants, Businesses, organizations and recreation sports.   " />
<meta name="verify-v1" content="8Uh2/XfCFI3RoUbDcYxpqYmuhgU5BEPWTR9wU9/KW2s=" />
<META name="y_key" content="e942681ff1bcbaa0" />
<meta name="google-site-verification" content="me4lHSEOfkOBWZv8XWPLHtq2mpGu4a3eQ0kipoCjjqw" />
<LINK REL="SHORTCUT ICON" HREF="http://4monmouth.com/images/icons/4monmouth.ico"> 
<?php if($this->layout()->cols == 2){ ?>
    <link rel="stylesheet" type="text/css" media="all" href="/css/layout/2column.css" />
    <link rel="stylesheet" type="text/css" media="all" href="/css/admin.css" />
<?php } else if ($this->layout()->cols == 1) {?>
    <link rel="stylesheet" type="text/css" media="all" href="/css/layout/1column.css" />
<?php } else {?>
    <link rel="stylesheet" type="text/css" media="all" href="/css/layout/3column.css" />
<?php } ?>
<link rel="stylesheet" type="text/css" media="all" href="/css/base.css" />
<link rel="stylesheet" type="text/css" media="all" href="/css/styles/index.css" />
<link rel="stylesheet" type="text/css" media="all" href="/js/jquery/jquery-ui-1.7.2.custom.css" />
<link rel="stylesheet" type="text/css" media="all" href="/js/colorbox/colorbox.css" />
<script src="/js/prototype.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-ui-1.7.2.custom.min.js" type="text/javascript"></script>
<script src="/js/colorbox/jquery.colorbox.js" type="text/javascript"></script>
<?php if(!isset($this->layout()->maps) || $this->layout()->maps != false){ ?>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<? } ?>
<script>
jQuery.noConflict();
</script>
<script src="/js/scriptac/scriptaculous.js" type="text/javascript"></script>
<script src="/js/FM.js" type="text/javascript"></script>
<script src="/js/tabs/tabs.js" type="text/javascript"></script>
<script src="/js/account.js" type="text/javascript"></script>
<script src="/js/banner.js" type="text/javascript"></script>
<script src="/js/scroller.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/widgets/admin.js"></script>
<script type="text/javascript" src="/js/widgets/photogallery.js"></script>
<?php echo $this->headScript() ?>
<script src="/js/slidingbanner.js" type="text/javascript"></script>
<script>var error = <?php echo (array_key_exists('error', $_GET)) ? 'true' : 'false'; ?></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18047248-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<body style="background-color:#<?php echo $this->layout()->background?>">

<div id="wrapper" style="position:relative;">
	<div id="header">
	<?php $login = (isset($this->layout()->name)) ? 'Account' : 'Login'; ?>
	     <div id="topBar">
	     	<?php if(isset($this->layout()->name)){ ?>
	     	<a>welcome <?php echo $this->layout()->name?>&nbsp;</a>
	     	<?php
	     	}?><a href="/mission">Mission</a> <a href="/affiliates">Affiliates</a> <a href="/feedback">Feedback</a> <a href="/faqs">FAQ</a> <a href="/contact">Contact Us</a> <a href="/account"><?php echo $login; ?></a><!-- <a onclick='Shadowbox.open({content:"http://208.82.128.17/admin/banner", player:"iframe"});'>admin</a>-->
	     	<?php if(isset($this->layout()->name)){ ?>
	     	<a href="/access/logout/" class="logout">Logout</a>
	     	<?php
	     	} ?>
		</div>
		<div id="titleWrap">
		<?php if(!$this->layout()->admin){ ?>
			<div id="headerTitle">
		    	<!--<span class='green'>4</span>Monmouth<span class='green'>.com</span>-->
				<a href="/" ><img src="/images/logo_piccolo.png" /></a>
		   		<!--<div class="byline">Great Towns. Great Savings.</div>-->
		    </div>
		    <ul id="layoutdims">
				<li class="home"><a href="/">Home</a></li>
				<li class="search"><a href="/search/">Search Page</a></li>
				<li class="services"><a href="/ourservices">Our Services</a></li>
				<li class="presents"><a href="<?php echo $this->layout()->mediakit; ?>"><img src="/images/4m-presents3.png" border="0" /></a></li>
			</ul>
		<?php } ?>
		</div>