<?php
	echo $this->partial('header.phtml');
?>
<div id="dhtmltooltip"></div>
<script>
	var tipobj= $('dhtmltooltip')
</script>

<?php if($this->layout()->fullBanner) { ?>
<div id="titleBanner">
<?php if(stristr($this->layout()->fullBanner->getFile(), '.swf')){ ?>
					<object width="952" height="120"><param name="movie" value="/media/image/fullbanners/<?php echo $this->layout()->fullBanner->getFile(); ?>"><param name="wmode" value="transparent"><embed src="/media/image/fullbanners/<?php echo $this->layout()->fullBanner->getFile(); ?>" width="952" height="120" wmode = 'transparent'></embed></object>
			 <?php }else{ 
			 	
			 	
    if($link = $this->layout()->fullBanner->getLink()){echo "<a href='{$link}' target='_blank'>";} ?>
	   <img src="/media/image/fullbanners/<?php echo $this->layout()->fullBanner->getFile() ;?>" />
    <?php if($link) { ?></a><?php } ?>
</div>
<?php } } ?>
</div>
<div id="<?php echo $this->pageId; ?>" class="crusade">
    <div id="crumbWrap">
        <?php echo $this->crumb; ?>
    </div>
    <div class="subnav">
        &nbsp;
    </div>
    <div class="bzHeader">
        <img src="/media/image/logos/<?php echo ($l = $this->layout()->logo) ? $l : 'DefaultminiwebLogo.jpg' ?>" width="238" /><img src="<?php echo ($l = $this->layout()->miniwebBanner) ? '/media/image/logos/' . $l : '/images/temp/DefaultBanner.jpg' ?>" width="663" />
    </div>
    <div id="colwrap" class="sm">
        <div class="col1">
            <!-- Column 2 start -->
            <?php echo $this->layout()->content ?>
            <!-- Column 2 end -->
        </div>
        <div class="col2">
            <!-- Column 1 start -->
            <?php echo $this->layout()->leftcol ?>
            <!-- Column 1 end -->
        </div>
    </div>
	
	<div class="subfooter">
		 <?php echo $this->crumb; ?>
	</div>
</div>
<?php
	echo $this->partial('footer.phtml');
?>
