<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>4 Monmouth.com! Administrative Area </title>
<meta name="keywords" content="momouth county" />
<meta name="description" content="A site for Monmouth County " />
<meta name="verify-v1" content="8Uh2/XfCFI3RoUbDcYxpqYmuhgU5BEPWTR9wU9/KW2s=" />
<link rel="stylesheet" type="text/css" media="all" href="/css/rootadmin.css" />
<link rel="stylesheet" type="text/css" media="all" href="/css/root/all.css" />
<link rel="stylesheet" type="text/css" media="all" href="/js/jqueryui/jquery-ui-1.7.2.custom.css" />
<link rel="stylesheet" type="text/css" media="all" href="/js/colorbox/colorbox.css" />
<script src="/js/colorpicker.js" type="text/javascript"></script>
<script src="/js/prototype.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-ui-1.7.2.custom.min.js" type="text/javascript"></script>
<script src="/js/colorbox/jquery.colorbox.js" type="text/javascript"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>
jQuery.noConflict();
</script>
<script src="/js/foreign/phpserial.js" type="text/javascript"></script>
<script src="/js/scriptac/scriptaculous.js" type="text/javascript"></script>
<script src="/js/FM.js" type="text/javascript"></script>
<script src="/js/root/businessclient.js" type="text/javascript"></script>
<script src="/js/root/admin.js" type="text/javascript"></script>
<script src="/js/faqs/faqs.js" type="text/javascript"></script>
<script src="/js/root/ajaxupload.js" type="text/javascript"></script>
<script src="/js/root/coupon.js" type="text/javascript"></script>
<script src="/js/root/banner.js" type="text/javascript"></script>
<script src="/js/root/user.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/js/root/utilities.js"></script>
<script type="text/javascript" src="/js/root/feedback.js"></script>
<script type="text/javascript" src="/js/widgets/banner.js"></script>
<?php echo $this->headScript() ?>
</head>

<body>
<div id="statusMessage"></div>
<div id="main">
	<div id="header">
		<!--<a href="index.html" class="logo"><img src="/images/root/img/logo.gif" width="101" height="29" alt="" />
			4Monmouth Administration Area
		</a>-->
		<h1 class="headline">
			<span>4</span>Monmouth<span>.com</span>
		</h1>
		<h2 class="byline">Administration Area</h2>

		<ul id="top-navigation">
			<li <?php echo ($this->home) ? 'class="active"' : '' ?>><span><a href="/root/admin">Homepage</a></span></li>
			<li <?php echo ($this->cat) ? 'class="active"' : '' ?>><span><a href="/root/managecategories">Categories</a></span></span></li>
			<li <?php echo ($this->org) ? 'class="active"' : '' ?>><span><a href="/root/addbusiness">Organizations</a></span></li>
			<li <?php echo ($this->users) ? 'class="active"' : '' ?>><span><a href="/root/manageusers">Users</a></span></li>
			<!--<li <?php echo ($this->faq) ? 'class="active"' : '' ?>><span><a href="/root/managefaq">Faqs</a></span></li>-->
			<li <?php echo ($this->util) ? 'class="active"' : '' ?>><span><a href="/root/missionstatement">Utility Pages</a></span></li>
			<!--<li><span><span><a href="/root/checkemail">Email</a></span></span></li>-->
			<li <?php echo ($this->coupon) ? 'class="active"' : '' ?>><span><a href="/root/managecoupons">Coupons</a></span></li>
			<li <?php echo ($this->banner) ? 'class="active"' : '' ?>><span><a href="/root/managebanners">Banners</a></span></li>
			<!--<li <?php echo ($this->feedback) ? 'class="active"' : '' ?>><span><a href="/root/feedback">Feedback</a></span></li>-->
		</ul>
	</div>
	<div id="middle">
		<div id="left-column">
			<?php if(isset($this->sidenav)) {
				echo $this->sidenav;
			} else {	?>
				<h3>Root Admin</h3>
			<?php }?>
		</div>
		<div id="center-column">
			<div id="confirmation"></div>
				<?php echo $this->layout()->content ?>
			</div>
			<!--
			<div id="right-column">
				<strong class="h">INFO</strong>
				<div class="box">Detect and eliminate viruses and Trojan horses, even new and unknown ones. Detect and eliminate viruses and Trojan horses, even new and </div>
		  </div> -->
	</div>
	<div id="footer">&nbsp; </div>
</div>

<?php 
	if($this->tiny) { ?>
		<script type="text/javascript">
		var tiny = tinyMCE.init({
			// General options
			width: "300px",
			mode : "textareas",
			theme : "advanced",
			plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,imagemanager,filemanager",
		
			// Theme options
			theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,link,unlink,anchor,image,cleanup,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,|,sub,sup,|,charmap,iespell,media,advhr",
			theme_advanced_buttons4 : "absolute,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,nonbreaking,blockquote,pagebreak,ltr,rtl,|,emotions,fullscreen,code,preview,print,help",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,
		
			// Example content CSS (should be your site CSS)
			content_css : "css/example.css",
		
			// Drop lists for link/image/media/template dialogs
			template_external_list_url : "js/template_list.js",
			external_link_list_url : "js/link_list.js",
			external_image_list_url : "js/image_list.js",
			media_external_list_url : "js/media_list.js",
		
			// Replace values for the template plugin
			template_replace_values : {
				username : "Some User",
				staffid : "991234"
			}
		});
		</script>
<? } ?>

</body>
</html>