<div class="orgdata">
<?php //print_r($org);exit; ?>
	<h1><? echo $this->org->get('name'); ?></h1>
    
	 <?php if($this->org->get('address1') || $this->org->get('city') || $this->org->get('state') || $this->org->get('zip')) { ?>
		<div class="address">
	        <div><? echo $this->org->get('address1'); ?></div>
	        <div><? echo $this->org->get('city'); ?> <? echo $this->org->get('state'); ?> <? echo $this->org->get('zip'); ?></div>    
	    </div>
     <?php } ?>
     <?php if($this->org->get('phone') || $this->org->get('fax') ) { ?>
    <div class="info">
     <?php if($this->org->get('phone')) { ?>
        <div>
            <label>Phone:</label>
            <? echo $this->org->get('phone'); ?>
        </div>
         <?php } ?>
        <?php if($this->org->get('fax')) { ?>
        <div>
              <label>Fax:</label>
              <? echo $this->org->get('phone'); ?>
         </div>
          <?php } ?>
    </div>
     <?php } ?>
	 <?php if($this->org->get('email')) { ?>
	<div>
	        <label>Email:</label>
            <a href="mailto:<? echo $this->org->get('email'); ?>"><? echo $this->org->get('email'); ?></a>
    </div>
     <?php } ?>
    <?php if($this->org->get('website')) { ?>
    <div>
	        <label>Website:</label>
            <a href="<? echo $this->org->getFormattedWebsite(); ?>" target="_blank"><? echo str_replace('www.' , '' ,$this->org->get('website')); ?></a>
    </div>
    <?php } ?>
</div>