<div class="<?php echo $this->obj->getClass(); ?>">
				<div class="cpnImg"><img src = "/media/image/couponlogos/<?php echo $this->obj->getFile(); ?>" /></div>
				<div class="cpnSponsor"><?php echo $this->obj->getSponsor(); ?></div>
				<div class="cpnOffer"><?php echo $this->obj->getOffer(); ?></div>
				<?php if($this->obj->getValid()) { ?>
					<div class="clear"></div>
					<div class="cpnValid"><span>Ends:</span> <?php echo $this->obj->getFormattedValid(); ?></div>
				<?php } ?>
				<div class="cpnCopy"><?php echo $this->obj->getCopy(); ?></div>
				<div class="clear">&nbsp;</div>
				<div style="text-align:right;" ><img src="/media/image/coupon_templates/logo_coupon_orizzontal.png" /></div>
</div>