<div id="featuredorg">
	<div class="inner">
		<h4>MEET THE ORGANIZATION</h4>
		<div class="img">
			<a href="/org/<?php echo $this->organization->get('id'); ?>"><img src="/media/image/icons/<?php echo ($k = $this->organization->getIconObj()->getFileName()) ? $k : 'searchNoLogo.gif'; ?>"></a>
		</div>
		<div class="smallHead"><?php echo $this->organization->get('name'); ?></div>
		
		<div><?php echo substr(strip_tags($this->organization->get('description')), 0 , 200); ?>...</div>
		<div style="text-align:right;clear:both;"><a href="/org/<?php echo $this->organization->get('id'); ?>">read more</a></div>
		
	</div>	
</div>