<div id="spotlight">
    <div class="inner">
        <h4>Business Spotlight</h4>
        <?php
			foreach ($this->organizations as $index=>$org) {
		        ?>
		        <div class="spotlightWrapper">
		        <a href="/merchant/<?php echo $org->get('id'); ?>">
		            <div class="img">
		                <img src="/media/image/icons/<?php echo $org->getIconImage(); ?>">
		            </div>
		            <div class="smallHead">
		                <?php echo ucwords(strtolower(stripslashes($org->get('name')))); ?>
		            </div>
		            <div class="desc">
		                <?php echo (stristr($org->get('description'), 'Not A Member')) ? '' : ucwords(strtolower(substr(strip_tags(stripslashes($org->get('description'))), 0 , 100))) . '...'; ?>
		               
		            </div>
		            </a>
		        </div>
		        <?php
			}
        ?>
        <div class="clear">&nbsp;</div>
    </div>
</div>
