	<?php $header = ($this->header)? '/media/image/auxpage_headers/' . $this->header: '/images/mission/mission_head.jpg'; ?>
<div id="subheader">
	    <div class="holder">
	        <img src="<?php echo $header; ?>" />
	    </div>
	    <div class="orgLinks">
	        <a href="/aboutus"><img src="/images/corporate/about4monmouth.gif" /></a><a href="/forusers"><img src="/images/corporate/4users.gif" /></a><a href="/fororganizations"><img src="/images/corporate/4orgs.gif" /></a><a href="/foradvertisers"><img src="/images/corporate/4advertisers.gif" /></a>
	    </div>
	</div>
</div>