<?php 
//print_r($this->banners);exit;
	foreach ($this->banners as $banner) { 
		?>
	<?php $template = $banner['template'];?>
	<div class="sponsors <?php echo $template['class']; ?>">
	<?php if($banner['url']) {?>
		<a href="http://<?php echo $banner['url']; ?>" <?php if(!stristr($banner['url'], '4monmouth.com')){echo 'target="_blank"';} ?>>
	<?php } ?>
	<?php
		if($template['logo'] == 1) {
			$alt = ($banner['alt'] != '') ? 'alt="'.$banner['alt'].'"' : ''?>
			<img src="<?php echo $banner['path'] . '/' . $banner['medianame']; ?>"  <?php echo $alt; ?> />
	<?php } ?>
	<?php
		if($template['headline'] == 1 && $banner['headline'] != '') {
			echo "<h1>{$banner['headline']}</h1>";
		}
		?>
		<div class="copy">
			<?php echo $banner['copy']; ?>
		</div>
		<?php if($banner['url']) {?>
		</a>
	<?php } ?>
	</div>
<?php 	}
?>