<div class="rssglobal <?php echo $this->class ?>" id="<?php echo $this->id ?>">
    <div class="inner">
        <h3>
            <?php echo $this->title; ?>
        </h3>
        <?php 
			$i = 1;
			$j = 0;
			foreach($this->rod as $item) {
				if($j < $i) {
					$img =  $this->rod->image;
					print '<img src="' . $img->url->__toString() . '" height="50" width="50">';
					print '<div class="rodtitle">' . $item->title . '</div>';
					//print "<div class='link'>| <a onclick='Shadowbox.open({content:\"{$item->link()}\", player:\"iframe\"});' >{$item->title()}</a></div>";
				}
				if($i > 0) {
					$j++;
				}
			}
        ?>
    </div>
</div>
