<div class="clientLists">
<h3>Businesses</h3>
<?php print $this->catJumper; ?>
<?php print $this->search; ?>
<div>	
	<ul class="client_nav">
				<li class="addBizClient" id="addClientList">Add A Client</li>
				<li class="bizClient" id="clientList">Client List</li>
	</ul>	
		<div id="bizClients" class="client active">
			<?php print $this->clients; ?>
		</div>
		
		<div id="addBizClients" class="client">
			<?php print $this->form; ?>
		</div>		
	</div>
	
</div>
<?php
	if($this->error) {
		print "<script>FM.Client.toggleNav($('addClientList'))</script>";
	}
?>

<script language="JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
if (restore) selObj.selectedIndex=0;
}
//-->
</script>
              