<div class="clientLists">
<h3>Non-Profits</h3>
<?php print $this->catJumper; ?>
<?php print $this->search; ?>
	<ul class="client_nav">
				<li class="npClient" id="clientList">Client List</li>
				<li class="addNpClient" id="addClientList">Add A Client</li>
	</ul>
	
	<div>
		<div id="npClients" class="client active">
			<?php print $this->clients; ?>
		</div>
		
		<div id="addNpClients"  class="client">
			<?php	print $this->form;	?>
		</div>		
	</div>
	
</div>
<?php
	if($this->error) {
		print "<script>FM.Client.toggleNav($('addClientList'))</script>";
	}
?>
<script language="JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
if (restore) selObj.selectedIndex=0;
}
//-->
</script>