<style>
h1 {visibility:visible; top:30px; font-family: "Trebuchet MS", Skia, "Lucida Sans Unicode", sans-serif; font-size: x-large;}
div#wheel {visibility:visible;  width: 256px; height: 256px;}
div#demoa, div#demob, div#democ {visibility:visible; top:360px; width: 256px; height: 75px; text-align: center; padding-top: 15px; padding-bottom: 200px;}
div#demoa {left:80px; margin-right: 0px;}
div#demob {left:165px; margin-left: 0px;  margin-right: 0px;}
div#democ {left:250px; margin-left: 0px;}

div#rights {visibility:visible; top:140px; left:375px;}
div#picks {padding-left: 35px; border-left: 1px dotted grey;}
div#picka, div#pickb, div#pickc, div#pickd, div#picke, div#pickf, div#pickg {width: 200px; height: 200px; padding: 10px;margin-top:.5em;background-color:#<?php echo $this->siteconfig->getBackground(); ?>;}
div#instructs {padding-bottom: 30px; font-family: "Trebuchet MS", Skia, "Lucida Sans Unicode", sans-serif;}
div#notes {padding-top: 30px; font-size: smaller;}

.btxt {color: #000000;}
.wtxt {color: #ffffff;}
</style>

<h2>Choose Site Background Color</h2>
<div style="width:500px;margin-top:1em;">
<div style="margin:0px auto;">
<!-- on the left, the wheel and display -->
<div style="width:300px;float:left;">
	<div id="wheel">
		<a href="javascript://" onclick="javascript:pickColor(); return false"><img src="/images/colorwheel.png" alt="color wheel" width="256" height="256" border="0"></a>
	</div>
	<div id="demoa">
		<form name="cccform">
			<input type="text" name="ccc" size="9">
		</form>
		<span class="btxt">web-safe</span><br>
		<span class="wtxt">web-safe</span>
	</div>
</div>

<!--
<div id="demob">
<form name="aaaform">
<input type="text" name="aaa" size="9">
</form>
<span class="btxt">web-smart</span><br>
<span class="wtxt">web-smart</span></div>

<div id="democ">
<form name="abcform">
<input type="text" name="abc" size="9">
</form>
<span class="btxt">unsafe</span><br>
<span class="wtxt">unsafe</span></div>
-->
<!-- on the right, the picks and instructions -->
<div style="width:200px;float:right;">
	<div id="rights">
		<div id="instructs">
			<p>Hover over the wheel to view colors.<br>
			Click to choose a web-smart color.<br></p>
		</div>
	</div>
	<div id="picks">
	<p>
		<h4>You Chose :</h4>
	</p>
	<div id="picka"><tt class='wtxt'>#<?php echo $this->siteconfig->getBackground(); ?></tt><br><tt class='btxt'>#<?php echo $this->siteconfig->getBackground(); ?></tt></div></div>
	<div style="margin-top:.5em;text-align:right;">
		<input type="submit" value="submit change" onclick="changebackground($('picka'))" />
	</div>
</div>
</div>

</div>
<script>
	FM.onDomReady(capture);
</script>
</div>
</div>