<?php echo $this->form; ?>
<div  id="users" class="mod managesiteemails">
<table width="100%" class="listing">
<tr><th>name</th><th>email</th><th>edit</th><th>delete</th></tr>
<?php
	foreach ($this->emails as $email) {
		echo "<tr><td>{$email->getName()}</td><td>{$email->getEmail()}</td><td><img src = '/images/icons/edit.png' onclick='FM.Utilities.editSiteEmail(\"{$email->getId()}\",\"{$email->getName()}\", \"{$email->getEmail()}\")' /></td><td><a href='/root/managesiteemails/delete/{$email->getId()}'><img src='/images/icons/remove.png' /></a></td></tr>";
	}
?>
</div>
</table>