<div class="bannerLists">
	<h3>Manage Banner Templates</h3>
	<div id="banners">
		<h4>Banner Templates</h4>			
		<div class="lists">
			<div class="table">
				<table class="listing" cellpadding="0" cellspacing="0">
					<tbody>
						<tr>
							<th class="id">Id</th>
							<th class="name">Name</th>
							<th>Active</th>
							<th>Delete</th>
						</tr>
						<?php foreach ($this->templates as $template) { ?>
						<tr id="tr_<?php echo $template->getId() ?>">
							<td class="id"><?php echo $template->getId() ?></td>
							<td class="name nowidth"><a class="preview_banner" href="/media/image/banner_templates/<?php echo $template->getImage() ?>"><?php echo $template->getName() ?></a></td>
							<td class="active"><input id="active_<?php echo $template->getId() ?>" type="checkbox" onclick="FM.BannerRoot.toggleTemplateActive(<?php echo $template->getId() ?>)" <?php echo ($template->isActive())? 'CHECKED' : ''; ?> /></td>
							<td class="delete"><div onclick="FM.BannerRoot.deleteBannerTemplate(<?php echo $template->getId() ?>)"><img src="/images/icons/remove.png" alt="add" height="16" width="16"></div></td>
						</tr>
						<?php } ?>				
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
