<div class="bannerLists">
	<div class="coupon_nav">
		<form>Show Pay Banners On Site? <input type="checkbox" id="usepaybanners" onclick="FM.BannerRoot.toggleUsePaybanner()" <?php echo ($this->enabled) ? 'CHECKED' : '' ?> /></form>
	</div>
	<h3>Add a Pay Banner</h3>
	<?php echo $this->search; ?>
	<?php if($this->sizeError) {print '<div>Images must measure exactly 514x50 pixels. Please try again';} ?>
	<?php echo $this->addForm; ?>	
	<h3>Manage Pay Banners</h3>
	<div id="banners">
		<h4>Banners</h4>			
		<div class="lists">
			<div class="table">
				<table class="listing" cellpadding="0" cellspacing="0">
					<tbody>
						<tr>
							<th class="id">Id</th>
							<th class="name">Name</th>
							<th>Active</th>
							<th>Delete</th>
						</tr>
						<?php foreach ($this->banners  as $index=>$banner) { ?>
						<tr id="tr_<?php echo $banner->getId() ?>">
							<td class="id"><?php echo $banner->getId(); ?></td>
							<td class="name nowidth"><a class="preview_banner" href="/media/image/paybanners/<?php echo $banner->getFile() ?>"><?php echo $banner->getName() ?></a></td>
							<td class="active"><input id="active_<?php echo $banner->getId() ?>" type="checkbox" onclick="FM.BannerRoot.togglePaybannerActive(<?php echo $banner->getId() ?>)" <?php echo ($banner->isActive())? 'CHECKED' : ''; ?> /></td>
							<td class="delete"><div onclick="FM.BannerRoot.deletePayBanner(<?php echo $banner->getId() ?>)"><img src="/images/icons/remove.png" alt="add" height="16" width="16"></div></td>
						</tr>
					<?php } ?>				
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>