<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>4 Monmouth.com! </title>
<meta name="keywords" content="momouth county" />
<meta name="description" content="A site for Monmouth County " />
<meta name="verify-v1" content="8Uh2/XfCFI3RoUbDcYxpqYmuhgU5BEPWTR9wU9/KW2s=" />
<link rel="stylesheet" type="text/css" media="all" href="/css/root/lite.css" />
<script src="/js/prototype.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-ui-1.7.2.custom.min.js" type="text/javascript"></script>
<script src="/js/colorbox/jquery.colorbox.js" type="text/javascript"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>
jQuery.noConflict();
</script>
<script src="/js/FM.js" type="text/javascript"></script>
<script src="/js/root/quickadd.js" type="text/javascript"></script>
<script src="/js/root/user.js" type="text/javascript"></script>
</head>
<body id="newUser">
	<h3>Create New Member</h3>
	<div class="client">
		<?php echo $this->form; ?>	
	</div>
</body>