<h3>User: <?php echo $this->member->getUserName() ?></h3>
<div id="users" class="details">	
	<h4>Details</h4>
	<div class="lists">
		<?php if($this->member) { ?>
		<table class="listing">
			<tr>
				<th colspan="2" align="left"><? echo $this->member->getFirstName() ?> <?php echo $this->member->getLastName() ?></th>
			</tr>
			<tr>
				<td class="key">First Name</td>
				<td class="value"><?php echo $this->member->getFirstName() ?></td>
			</tr>
			<tr class="odd">
				<td class="key">Middle Name</td>
				<td class="value"><?php echo $this->member->getMiddleName() ?></td>
			</tr>
			<tr>
				<td class="key">Last Name</td>
				<td class="value"><?php echo $this->member->getLastName() ?></td>
			</tr>
			<tr class="odd">
				<td  class="key">Address 1</td>
				<td class="value"><?php echo $this->member->getAddress1() ?></td>
			</tr>
			<tr>
				<td  class="key">Address 2</td>
				<td class="value"><?php echo $this->member->getAddress2() ?></td>
			</tr>
			<tr class="odd">
				<td  class="key">City</td>
				<td class="value"><?php echo $this->member->getCity() ?></td>
			</tr>
			<tr>
				<td  class="key">State</td>
				<td class="value"><?php echo $this->member->getState() ?></td>
			</tr>
			<tr class="odd">
				<td  class="key">Zip</td>
				<td class="value"><?php echo $this->member->getZip() ?></td>
			</tr>
			<tr>
				<td  class="key">Phone</td>
				<td><?php echo $this->member->getPhone() ?></td>
			</tr>
			<tr class="odd">
				<td  class="key">Email</td>
				<td class="value"><?php echo $this->member->getEmail() ?></td>
			</tr>
			<tr>
				<td  class="key">Mailling List</td>
				<td class="value"><?php echo ($this->member->wantsMail()) ? 'YES' : 'NO' ?></td>
			</tr>
			<tr class="odd" style="height:auto;">
				<td  class="key" valign="top">Organizations:</td>
				<td class="value" height="100%">
					<div style="height:150px;overflow:scroll;">
					<?php
					foreach ($this->orgs as $o) { 
							if(is_object($o) && $o->getId()) {?>
								<div id="org_<?php echo $o->getId() ?>" style="clear:both;">
									<?php echo $o->getName() ?>
									<a onclick="FM.UserRoot.removeFromOrg($('uid').value , <?php echo $o->getId() ?>)">
										<img src="/images/icons/remove.png" height="16" width="16">
									</a>
								</div>
					<?php
							}
						}?>
					</div>
					<div style="clear:both;">&nbsp;</div>
					<hr />
				</td>
			</tr>
		</table>
		<div style="clear:both;">&nbsp;</div>
		<?php	} else {	?>
		<p>Member Does Not Exist</p>
		<a class="anchor" href="/root/manageusers"><- back</a>
	<?php
	}
	?>
	</div>
	<div style="clear:both;">&nbsp;</div>
</div>


<?php if($this->member) { ?>
	<form>
		<div class="mod">
			<h4>Edit Information</h4>
			<div>
				<label>Details :</label>
				<select id="details">
					<option value="0">Choose A Detail To Edit</option>
					<option value="firstname">First Name</option>
					<option value="middlename">Middle Name</option>
					<option value="lastname">Last Name</option>
					<option value="address1">Address 1</option>
					<option value="address2">Address 2</option>
					<option value="city">City</option>
					<option value="zip">Zip</option>
					<option value="phone">Phone</option>
					<option value="email">email</option>
				</select>
			</div>
			<div>			
				<label>New Value : </label>
				<input type="text" id="newValue" class="newValue"/ >
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit" onclick="FM.UserRoot.updateDetails();return false;"  />
			</div>
		</div>
	</form>
	
	<form>		
		<div class="mod">			
			<h4>Change Password</h4>
			<div>
				<label>New Password : </label>
				<input type="password"  id="pwd1" class="newValue"/>
			</div>
			<div>
				<label>Confirm : </label>
				<input type="password" id="pwd2" class="newValue"/>
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit" onclick="FM.UserRoot.updatePassword();return false;"  />
			</div>
		</div>
	</form>
	
	<form>
		<div class="mod">
			<h4>Add To Organization</h4>
			<div>
				<label>Organization : </label>	
				<select id="borgSelect">
				<option value="">Select A Business</option>
				<?php
					foreach ($this->borgs as $org) {?>
						<option value="<?php echo $org['id'] ?>"><?php echo ucwords($org['name']) ?></option>
					<?}?>
				</select>
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit" onclick="FM.UserRoot.addToOrg($('uid').value ,$('borgSelect').value, $('borgSelect'));return false;" />
			</div>			
			<div>
				<label>Organization : </label>	
				<select id="nporgSelect">
				<option value="">Select A Non-Profit</option>
				<?php
					foreach ($this->nporgs as $org) {?>
						<option value="<?php echo $org['id'] ?>"><?php echo ucwords($org['name']) ?></option>
					<?}?>
				</select>
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit" onclick="FM.UserRoot.addToOrg($('uid').value ,$('nporgSelect').value, $('nporgSelect'));return false;" />
			</div>			
		
			<div>
				<label>Organization : </label>	
				<select id="sorgSelect">
				<option value="">Select A Sport</option>
				<?php
					foreach ($this->sportsorgs as $org) {?>
						<option value="<?php echo $org['id'] ?>"><?php echo ucwords($org['name']) ?></option>
					<?}?>
				</select>
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit" onclick="FM.UserRoot.addToOrg($('uid').value ,$('sorgSelect').value, $('sorgSelect'));return false;" />
			</div>			
		</div>	
	</form>
	
	
	<form>
		<div class="mod">
			<h4>MailingList</h4>
			<div>
				<label>Mailing List :</label>	
				<select>
					<option value="1" <?php echo ($this->member->wantsMail()) ? 'SELECTED' : '' ?>>YES!</option>
					<option value="0" <?php echo (!$this->member->wantsMail()) ? 'SELECTED' : '' ?>>NO!</option>
				</select>
			</div>
			<div class="sub">
				<input type="submit" class="subEdit" value="submit"  />
			</div>
		</div>
	</form>	
	
	<input type = "hidden" id="uid" value = "<?php echo $this->member->getId(); ?>" />
	
<?php } ?>