<div class="horoscope" id="full">
	<div class="inner">
		<h4>Horoscope</h4>
	    <div class="signs">
	        <?php 
		$i = 0;
		foreach ($this->signs as $item) {
				$title = str_replace('- by Astrocenter.com', '', $item->getTitle());
				$imgTitle = str_replace(' ', '', $title);
				$imgTitle = str_replace('DailyHoroscope:' , '', $imgTitle);
				print '<a class="horoscope" href="'.$item->getLink().'"><img src="/images/astrology/' . strtolower($imgTitle) . '-sign-small.gif" ></a>';
				if($i == 3) {
					print '<br />';
					$i=0;
				} else {
					$i++;
				}
			}
	        ?>
	    </div>
	</div>
</div>