<div  id="faqs">
	<h4>Answers</h4>
	<div class="lists">
		<a class="anchor" href="#form">back to form</a>
		<table>
			<tr>
				<th class="qa">Question / Answer</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<?php
			$count =0;
			foreach($this->faqs as $index=>$faq) { 
				$count++;
			?>
			<tr id="q_<?php echo $faq->getId(); ?>">
				<td class="q"></span><?php echo $faq->getQuestion(); ?></td>
				<td class="edit"><img class="edit_faq" id="qa_edit_<?php echo $faq->getId(); ?>" src="/images/icons/edit.png" /></td>
				<td class="delete"><img class="delete_faq" id="qa_delete_<?php echo $faq->getId(); ?>" src="/images/icons/remove.png" /></td>
			</tr>
			<tr id="a_<?php echo $faq->getId(); ?>" class="odd">
				<td colspan="3" class="a"><?php echo $faq->getAnswer(); ?></td>
			</tr>
			<?php }?>
		
			</table>
			<!--<div id='del_<?php echo $faq->getId(); ?>'>
					<div class="questionWrap" style="cursor:pointer;" onmouseover="$('a<?php echo $index; ?>').style.display = 'inline'" onmouseout="$('a<?php echo $index; ?>').style.display = 'none'">
						<a name="f<?php echo $index; ?>" class="question" ><?php echo $faq->getQuestion(); ?></a>
					</div>
					<div class="edit_delete"><a href="" id="faq_<?php echo $faq->getId(); ?>"   href="" onclick = "FM.Faq.Root.deletefaq(this);return false;" >Delete</a></div>
					<div class="answer" id="a<?php echo $index; ?>" style="display:none"><div style="clear:both;"><?php echo $faq->getAnswer(); ?></div></div>
				</div>-->
				
		<a class="anchor" href="#form">back to form</a>
	</div>
</div>