<script>
pg = {
selected : 'p_<?php echo $this->photo['id']; ?>',
json : <?php echo $this->pg; ?>
}
function advance() {
	if(!pg.json[pg.selected].next){return false}
	next = pg.json[pg.selected].next;
	pg.selected = next;
	if(!pg.json[pg.selected].next){$('advancea').style.display = 'none';$('advanceb').style.display = 'none'}
	$('pwrap').style.width = parseInt(pg.json[next].width) + 10;
	$('rewinda').style.display = 'inline';$('rewindb').style.display = 'inline';
	$('currentphoto').src = '/media/image/photogallery/' + pg.json[next].imageName
	$('pdesc').innerHTML = pg.json[next].tagline
}

function pprevious() {
	if(!pg.json[pg.selected].prev){return false}
	next = pg.json[pg.selected].prev;
	pg.selected = next;
	if(!pg.json[pg.selected].prev){$('rewinda').style.display = 'none', $('rewindb').style.display = 'none'}
	$('advancea').style.display = 'inline';$('advanceb').style.display = 'inline'
	$('pwrap').style.width = parseInt(pg.json[next].width) + 10;
	$('currentphoto').src = '/media/image/photogallery/' + pg.json[next].imageName
	$('pdesc').innerHTML = pg.json[next].tagline
}
</script>
<div style="min-width:800px;min-height:600px;text-align:center;padding-top:2em;background-image:url('/images/bgds/photogallery.gif');">
<div id="pwrap" style="width:<?php echo $this->photo['width'] + 10; ?>;margin:0px auto;">
<div style="padding:5px;"><a id="rewinda" onclick="pprevious();return false;" <?php if($this->first){print ' style="display:none" ';}?>><img src="/images/icons/previous.png" /></a>&nbsp;<a id="advancea" <?php if($this->last){print ' style="display:none" ';}?> onclick="advance();return false;"><img src="/images/icons/next.png" /></a></div>
<img id='currentphoto' src="/media/image/photogallery/<?php echo $this->photo['imageName']; ?>" />
<div id="pdesc"><?php echo $this->photo['tagline']; ?></div>
<div style="padding:5px;"><a id="rewindb" onclick="pprevious();return false;" <?php if($this->first){print ' style="display:none" ';}?>><img src="/images/icons/previous.png" /></a>&nbsp;<a id="advanceb" <?php if($this->last){print ' style="display:none" ';}?> onclick="advance();return false;"><img src="/images/icons/next.png" /></a></div>
</div>
</div>