<div class="subpage" id="feedback">
	<h4>Feedback</h4>
    <div class="content">
    <img class="heading" src="<?php echo $this->headerImg; ?>"/>
		<div class="submit">
			<h1>Submit Feedback</h1>
			<?php
				echo $this->message;
				echo $this->form;
			?>
		</div>
		<div class="approvedFeedback" style="display:none">
			<h1>Previous Feedback</h1>
			<?php 
				foreach ($this->feedback as $key=>$feedback) { ?>
					<div class="feedback">
						<div class="mail"><?php echo $feedback->getEmail(); ?></div>
						<div class="date"><?php echo date('m-d-Y H:i', strtotime($feedback->getDate())); ?></div>
						<div class="clear">&nbsp;</div>
						<div class="feedbackCopy"><?php echo $feedback->getFeedback(); ?></div>
					</div>
				<?php }
			?>
		</div>    	
    </div>
</div>
