<style>
span.limehead {
	color:green;
}

div#limecardresults {
	font-size:9pt;
}

div#pagecount {
	text-align:right;
	color:green;
	font-size:11pt;
}

div#pagecount span {
	cursor:pointer;
}

div#pagecount span.selected {
	color:black;
}

</style>
<script>
function showpage(id, total) {
	for(i = 1; i<total; i++) {
	$('lc_' + (i * 12)).style.display = 'none';
	$('sp_' + i).className = '';
	}
	$('lc_' + (id * 12)).style.display = 'inline';
	$('sp_' + id).className = 'selected';
}
</script>
<div style="margin:.5em;">
<h2>The Lime Card is here!</h2>
<div style="margin-bottom:1em;">The Lime Card gets you discounts at your favorite merchants!<br />Use the search box below to see who is using it!</div>
<h4 style="padding:.5em .5em .5em 0;">Browse By Alphabet</h4>
<div>
<?php $selected = ($this->selected == '0') ? 'color:black;' : ''; ?>
<a href = '/limecard/alph/0' style="text-decoration:underline;font-size:8pt;<?= $selected ?>">ALL</a>&nbsp;
<? 
/**
$k = 0;
$str = '';
foreach(range('A','Z') as $i) {
	if($k < 2) {
		if($k == 1) {
			$str .= ' - ';
		}
		else {
			$str .= $i;
		}
		$k++;
	} else {
		$str .= $i;
			$k = 0; 
			**/
foreach(range('A','Z') as $i) {
	$selected = ($this->selected == $i) ? 'color:black;' : '';
?>
			<a href = '/limecard/alph/<?= $i ?>' style="text-decoration:underline;font-size:8pt;<?= $selected ?>"><?= $i ?></a>&nbsp;
	<?	$str = '';
	}
			?>

	
	
<? 
?>
</div>
<h4 style="padding:.5em .5em .5em 0;">Or Category</h4>
<? echo $this->form; ?>
<h4 style="padding:.5em .5em .5em 0;">Or Region</h4>
<? echo $this->regionsForm; ?>
<?
	if($this->results) {
		$i = 12;
		$total = count($this->results);
		//print_r($this->results);exit;
	?>
	<div id="limecardresults">
		<h3 style="padding-top:.5em;"><?=$total; ?> results for '<?=$this->searchTerm; ?>'</h3>
	<?	
		if($total > 12 ) {
			echo '<div id="pagecount">page: ';
			$r = ceil($total/12);
			$j = $r +1;
			$c = 1;
			while($r >= $c) {
				$class = ($c == 1) ? 'class="selected"' : '';
				print "<span onclick = 'showpage({$c}, {$j})' id='sp_{$c}' {$class}>{$c}</span>&nbsp;";
				$c++;
			}
			echo '</div>';
			
		}
	foreach ($this->results as $key=>$values) { ?>
			<? 
			if(array_key_exists('type', $values['record'])) {
				switch($values['record']['type']) {
					case 2:
						$link = 'merchant';
						break;
					case 3:
						$link = 'org';
						break;
					case 4:
						$link = 'sports';
						break;
				}
			}
			if($i%12 == 0) {
				$visible = ($i == 12) ? 'inline' : 'none';
				print "<div id='lc_{$i}' style='display:{$visible}'>";
				
			}
			?>
			<hr />
			<div>
				<span class='limehead'>Name: </span><?=$values['record']['name']; ?><br />
				
				<? if($values['record']['address1'] != '') { ?>
				<span class='limehead'>Address: </span><?=$values['record']['address1']; ?><br />
				<? } ?>
				<? if($values['record']['city'] != '' && $values['record']['state'] != '' && $values['record']['zip'] != '') { ?>
				<span class='limehead'>City: </span><?=$values['record']['city']; ?>, <?=$values['record']['state']; ?> <?=$values['record']['zip']; ?><br />
				<? } ?>
				<? if($values['record']['phone'] != '') { ?>
				<span class='limehead'>Phone: </span><?=$values['record']['phone']; ?><br />
				<? } ?>
				
				
				<? if($values['record']['website'] != '') { ?>
				<span class='limehead'>Website: </span><a href="<?=$values['record']['website']; ?>" target="_blank"><?=$values['record']['website']; ?></a><br />
				<? } if(array_key_exists('type', $values['record'])) {?>
				<span class='limehead'>4Monmouth Link: </span><a href="http://4monmouth.com/<?=$link?>/<?=$values['record']['id']; ?>">http://4monmouth.com/<?=$link?>/<?=$values['record']['id']; ?></a><br />
			<? } ?> 
				<span class='limehead'>Categories : </span>&nbsp;
				<?
				   $str = '';
				    foreach ($values['categories'] as $value) {
				    	if(!stristr($str, $value)) {
							$str .= $value . ', ';
				    	}
					}
					echo strtolower(substr($str, 0 , -2));
				?>
				<? if(array_key_exists('limits', $values['record']) && $values['record']['limits'] != '') { ?>
					<div><span class='limehead'>More Info : </span>&nbsp;<i><?=$values['record']['limits']; ?></i></div>
				<? } ?>
			</div>
	<?	if($i%12 == 11) {
				print "</div>";
				
			}
			$i++;
	}
	echo '</div>';
	}
	if($total%12) {
		echo '</div>';
	}
	?>
	</div>
	<script>
	var limecardselectcat = function(el) {
			window.location = '/limecard/cat/' + el.value;
	}
		var limecardselectregion = function(el) {
			window.location = '/limecard/region/' + el.value;
	}
	</script>
