<div class="subpage">
	<h4>Not Found</h4>
    <div class="content">
		<h2>We are sorry but this client can not be found</h2>
		<?php if($this->orgs) { ?>
		<h4 style='margin:.3em;margin-left:0px;'>Were you looking for : </h4>
			<div style='margin:2em;margin-top:.5em;'>
			<?php 	foreach ($this->orgs as $org) {
					switch($org['type']) {
						case 2 :
							$link = '<a href="/merchant/'. $org['id'] . '">'. $org['name'] . '</a>';
							break;
						case 3 :
							$link = '<a href="/org/'. $org['id'] . '">'. $org['name'] . '</a>';
							break;
						case 4 :
							$link = '<a href="/sports/'. $org['id'] . '">'. $org['name'] . '</a>';
							break;
						default :
							continue;
					}
					print "<div style='margin:.5em'>$link</div>";
				}
			?>
			</div>
		<?php } ?>
	</div>
</div>