<div class="tab_content" style="width:100%">
	<div id="coupons" style="width:500px;margin:0px auto;">
		<div style="text-align:right;margin:.5em;"><A HREF="javascript:window.print()">Click to Print Coupons</A></div>
		<table border="0" id="couponlayout">
		<?php  $i = 1;
		foreach($this->coupons as $index=>$obj){
			if($i == 1){print '<tr>';}
			print '<td valign="top">';
			?>
			<?php
			switch($obj->getType()) {
				case 1:
					print $this->partial('tabs/couponoptions/coupon1.phtml', array(
					'obj'=>$obj));
					break;
				case 2:
					print $this->partial('tabs/couponoptions/coupon2.phtml', array(
					'obj'=>$obj));
					break;
				case 3:
					print $this->partial('tabs/couponoptions/coupon3.phtml', array(
					'obj'=>$obj));
					break;
					break;
				case 4:
					print $this->partial('tabs/couponoptions/coupon4.phtml', array(
					'obj'=>$obj));
					break;
					break;
			}
			print '</td>';
			if($i==2){print '</tr>';$i--;}else {$i++;}
		}
		if($i==2){print '<td>&nbsp;</td></tr>';$i--;}else {$i++;}
		?>
	</table>
	<div style="text-align:right;margin:.5em;"><A HREF="javascript:window.print()">Click to Print Coupons</A></div>
	</div>
	<div class="clear">&nbsp;</div>
</div>

