
 <div class="viewevent_ve">
  <?php
 
                    print '<div class="event">
                    <div id="event_' . $this->event->getEventId() . '" class="event_details" >
								<div class="event_name">' . $this->event->getName() . '</div>
								<div class="event_time"><strong>Sponsor: </strong>' . $this->event->getOrgName() . '</div>
								<div class="event_time"><strong>Date: </strong>' . date('l - F j, Y', strtotime($this->event->getDate())) . '</div>
								<div class="event_time"><strong>Time: </strong>' . $this->event->getFormattedTime() . '</div>
								<div class="event_location"><strong>Location: </strong>' . $this->event->getLocation() .'</div>
								<div class="event_description"><strong>Description:</strong>'. $this->event->getDescription() .'</div>
							</div>
						</div>';
                   
                    ?>
                    </div>