<script type="text/javascript">
FM.PhotoGallery2 = (function(){
    var data,
    
    bindEvents = function(){
        
        jQuery("#tab_media").unbind("click", FM.PhotoGallery2.init);
        
        jQuery(".jcarousel-item a").colorbox({
            opacity : .4,
        });
        return false;  
    },
    init = function(){
        
        data = JSON.parse('<?php echo $this->json; ?>');
        jQuery("#photogallery_carousel").jcarousel({
          size:   data.length,
          itemLoadCallback : {
              onBeforeAnimation : itemLoadCallback
          }
        })
    },
    itemLoadCallback = function(carousel, state){
        for (var i = carousel.first; i <= carousel.last; i++) {
            if (carousel.has(i)) { continue; }    
            if (i > data.length) { break }
            carousel.add(i, itemSchema(data[i-1]));
        }
        
        bindEvents();
    },
    itemSchema = function(item){
        return '<a title="'+item.imageTitle+'" href="/media/image/photogallery/' + item.imageName+'"><img src="/media/image/photogallery/' + item.imageName + '" width="60" height="60" alt="' + item.imageName + '" /></a>';
    }
    
    jQuery(function(){
       
       jQuery("#tab_media").click(FM.PhotoGallery2.init);
   })
   
   return {
       init : init
   }
    
})();    
</script>




<div id="photogallery">
    
    <div id="photogallery_upload">
    
    <ul id="photogallery_carousel">
        
    </ul>
    
   <form>
       <label>description</label><textarea name="tagline"></textarea>
   </form>
    
    
    
    
    
    <div class="head">Photo Gallery <img src="/images/camera-clipart1.gif" height="24" width="35" alt="4Monmouth photo gallery" /></div>
    <?php if(count($this->photos)) { 
        $i = 0;
        ?>
    <div id="slides">
        <div id="slide">
        <?php if($this->count > 10 ) { ?>
            <a id="moveLeft" onclick="FM.PhotoGallery.down()" >&laquo;</a>
        <?php } ?>
            <?while($i < 10 && count($this->photos) > $i) {?><img src="/media/image/photogallery/<? echo $this->photos[$i]['imageName']; ?>" onclick="FM.PhotoGallery.focus(this)" alt="" /><? $i++; } ?>
        <?php if($this->count > 10 ) { ?>
            <a id="moveRight" onclick="FM.PhotoGallery.up()">&raquo;</a>
        <?php } ?>
        </div>
    </div>
    <div class="largeImage" style="text-align:center;"><img src="/media/image/photogallery/<? echo $this->photos[0]['imageName']; ?>" id="largeGalleryImage" onclick="FM.PhotoGallery.fullSize(this)" / alt="4Monmouth Large Image"></div>
    <div class="imageDesc">This is the descritpion for this image</div>
    
    <?php } else { ?>
        <div class="imageDesc">No Photos Avaialble</div>
    <?php } ?>
</div>    
<script type="text/javascript">
//FM.PhotoGallery.init(<?php echo $this->json; ?>);
</script>
<?php if($this->admin) { ?>
<div style="padding:2em;border:1px solid #8CC901;background:white;">
    <h1>Admin</h1>
    <div style="margin:1em">
        <h2>Upload Images</h2>
        <form>
            <div style="margin:1em">
                    <div id="photoswf"><div id="swfUploadPhotoGallery"></div></div>
                    <div id="photoimage">60 X 60</div>
                    <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
            <div class="clear">
            <div class="clear">&nbsp;</div>
                <label>Description : </label><br /><textarea id="tagline" cols="60" rows="5" style="border:2px solid #8CC901"></textarea>
                <div style="text-align:right;margin-right:3em;margin-top:.5em;"><input type="submit" value="submit" onclick="FM.PhotoGallery.addPhoto();return false;"/></div>
                <input type="hidden" id="photoname" value='' />
                <input type="hidden" id="photoheight"  value='' />
                <input type="hidden" id="photowidth" value='' />
            
            </div>
        </form>
    </div>
</div>
<? }?>



</div>