<h3>Banners</h3>
<ul class="nav">
	<li <?php print ($this->selected === 'manage') ? 'class="selected"' : '';?>><a href="/root/managebanners">Manage Banners</a></li>
	<li <?php print ($this->selected === 'managepay') ? 'class="selected"' : '';?>><a href="/root/managepaybanners">Manage Pay Banners</a></li>
	<li <?php print ($this->selected === 'managefull') ? 'class="selected"' : '';?>><a href="/root/managefullbanners">Manage Full Banners</a></li>
	<li <?php print ($this->selected === 'addtemplate') ? 'class="selected"' : '';?>><a href="/root/addbannertemplate">Add Templates</a></li>
	<li <?php print ($this->selected === 'managebannertemplates') ? 'class="selected"' : '';?>><a href="/root/managebannertemplates">Manage Templates</a></li>
</ul>
				