<h3>Coupons</h3>
<ul class="nav">
	<li <?php print ($this->selected == 'managecoupon') ? 'class="selected"' : '';?>><a href="/root/managecoupons">Manage Coupons</a></li>
	<li <?php print ($this->selected == 'addtemplate') ? 'class="selected"' : '';?>><a href="/root/addcoupontemplate">Add Templates</a></li>
	<li  <?php print ($this->selected == 'managetemplate') ? 'class="selected"' : '';?>><a href="/root/managecoupontemplates">Manage Templates</a></li>
</ul>
<!--
<a href="#" class="link">Link here</a>
<a href="#" class="link">Link here</a>
-->
				