<h3>Manage Users</h3>
<ul class="nav">
	<li <?php print ($this->selected === 0) ? 'class="selected"' : '';?>><a href="/root/manageusers">All</a></li>
	<li <?php print ($this->selected == 2) ? 'class="selected"' : '';?>><a href="/root/manageusers/2">Business</a></li>
	<li <?php print ($this->selected == 3) ? 'class="selected"' : '';?>><a href="/root/manageusers/3">Non-Profits</a></li>
	<li <?php print ($this->selected == 4) ? 'class="selected"' : '';?>><a href="/root/manageusers/4">Sports</a></li>
	<li <?php print ($this->selected == 5) ? 'class="selected"' : '';?>><a href="/root/adduser">Create A User</a></li>
</ul>
				