<h3>Utility Pages</h3>
<ul class="nav">
	<li <?php print ($this->selected === 'mission') ? 'class="selected"' : '';?>><a href="/root/missionstatement">Our Mission</a></li>
	<li <?php print ($this->selected === 'about') ? 'class="selected"' : '';?>><a href="/root/aboutus">About Us</a></li>
	<li <?php print ($this->selected === 'users') ? 'class="selected"' : '';?>><a href="/root/forusers">For Users</a></li>
	<li <?php print ($this->selected === 'orgs') ? 'class="selected"' : '';?>><a href="/root/fororganizations">For Organizations</a></li>
	<li <?php print ($this->selected === 'adv') ? 'class="selected"' : '';?>><a href="/root/foradvertisers">For Advertisers</a></li>
	<li <?php print ($this->selected === 'afi') ? 'class="selected"' : '';?>><a href="/root/affiliates">Affiliates</a></li>
	<li <?php print ($this->selected === 'pri') ? 'class="selected"' : '';?>><a href="/root/privacy">Privacy Policy</a></li>
	<li <?php print ($this->selected === 'leg') ? 'class="selected"' : '';?>><a href="/root/legal">Legal Notice</a></li>
	<li <?php print ($this->selected === 'services') ? 'class="selected"' : '';?>><a href="/root/ourservices">Our Services</a></li>
	<li <?php print ($this->selected === 'faq') ? 'class="selected"' : '';?>><a href="/root/managefaq">FAQ's</a></li>
	<li <?php print ($this->selected === 'fbk') ? 'class="selected"' : '';?>><a href="/root/feedback">Feedback</a></li>
	<li <?php print ($this->selected === 'limecard') ? 'class="selected"' : '';?>><a href="/root/limecard">Limecard</a></li>
</ul>

				