<?php if($this->sportsuser) {?>
	<div style="text-align:right;padding:3px;text-transform:capitalize;margin-bottom:1em;">
	<a style="font-size:9pt;" onclick="FM.Account.sportsRetrievePwd(<?php echo $this->sportsuser->getId() ?>)">retrieve password</a>&nbsp;&nbsp;
	<a style="font-size:9pt;" onclick="FM.Account.sportsShowUpdateBox()">change password</a>&nbsp;&nbsp;
	<a style="font-size:9pt;" onclick="FM.Account.sportsSignOut()">Sign Out</a>
	</div>
	<div style="border:1px solid grey;width:350px;float:right;display:none;margin-bottom:1em;" id="sportsUpdatePassword">
		<input type="hidden" id="suid" value="<?php echo $this->sportsuser->getId() ?>" />
		<ul id="passwordInfo">
		<li><label>Old Password : </label> <input type="password" id="oldSPwdConf" /></li>
		<li><label>New Password : </label> <input type="password" id="newSPwd" /></li>
		<li><label>Confirm : </label> <input type="password" id="newSPwdConf" /></li>
		<li><a class="update" id="updateBtn" onclick="FM.Account.sportsChangePwd(<?php echo $this->sportsuser->getId() ?>)">update</a><a class="update" id="updateBtn" onclick="$('sportsUpdatePassword').style.display = 'none'">cancel</a></li>
		</ul>	
		
		<div class="clear">&nbsp;</div>
	</div>
<?php }?>
<?php echo $this->layout()->profiletab; ?>
<?php //echo $this->layout()->comments; ?>
<?php echo $this->layout()->testimonials; ?>
<?php echo $this->layout()->profile; ?>
<?php echo $this->layout()->askus; ?>
<input type="hidden" id="orgId" value="<?php echo $this->orgId; ?>" />
<div>
	<?php 
	if(count($this->coupons)) {
		foreach ($this->coupons as $coupon) {
				if($coupon->isActive()) {?>
				<div>
					<img src="/media/image/coupons/<?php echo $coupon->getFile(); ?>" height="150" width="220" />
				</div>
	<?php 
				}
		}
	}
	?>
</div>