<!--
<dt id="admin-label"><label for="admin" class="required">Administrator :</label></dt>
<dd id="admin-element">
    <SELECT id="userSelect" name="admin">
    	<?php //foreach ($this->element->getMultiOptions() as $key=>$value) { ?>
    		<option value="<?php //echo $key; ?>"><?php //echo $value; ?></option>
    	<? //} ?>
    </SELECT>
    <span id="adminCreateNewmember">or <a onclick='Shadowbox.open({content:"/root/quickadduser", player:"iframe", width:"470px", height:"530px;"});'>Create New User</a></span>
 </dd>
 <?php if($this->element->getMessages()){ echo $this->formErrors($this->element->getMessages()); } ?>
-->

<? $header = ($this->nobox) ? 'Current Document' : 'Current Header'; ?>
<? $src = explode('/', $this->src);
$src = $src[count($src) - 1];
	?>
 <?php if(!trim($src) == ''){ ?>
<dt id="preview-label"><?php echo $header ?></dt>
<? $class = ($this->nobox) ? '' : 'preview_util'; ?>
<? $onclick = ($this->nobox) ? 'onclick="location.href = \'' . $this->src . '\'"' : ''; ?>
<dd id="preview-element">
	<img class="<?php echo $class ?>" src="/images/icons/preview.png" title="<?php print $this->src; ?>"  <?php print $onclick ?>> <span>(click to view)</span>&nbsp;&nbsp;&nbsp;&nbsp;<img  src="/images/icons/remove.png" title="" class="<?php print $this->type; ?>_<?php echo $src; ?>" onclick="FM.Utilities.deleteMedia('<?php print $this->type; ?>' , '<?php echo $src; ?>', '<?php echo $this->tool; ?>', this)" >
</dd>
<dd id="delete-element">
	
</dd>
<? } ?>
