<div class="subpage" id="publicFAQ">
	<h4>Frequently Asked Questions</h4>
    <div class="content">
    	<a href name="top"></a>
		<div class="questions">
			<h1>Questions</h1>
			<?php
			foreach($this->faqs as $index=>$faq) {
				$questionNumber = $index + 1;
			?>
				<div><a href="#f<?php echo $index; ?>"><?php echo $questionNumber . '. ' . $faq->getQuestion(); ?></a></div>
			<?php }?>
		</div>
		<div class="answers">
			<h1>Answers</h1>
			<?php
			foreach($this->faqs as $index=>$faq) { ?>
				<div><a name="f<?php echo $index; ?>" class="question" ><?php echo $faq->getQuestion(); ?></a></div>
				<div class="answer"><?php echo $faq->getAnswer(); ?></div>
				<div class="backtotop"><a href="#top">Back To Top</a></div>
			<?php }?>
		</div>    	
    </div>
</div>