<div id="events_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Calendar / Events <a onclick='FM.Account.showhelp(this, "CALENDAR", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="calendarAdmin" class="module">
	<form name="addEvent" id="addEvent" class="zend_form">
		<div <?php echo ($this->type == 4)? 'style="display:none"' : ''; ?>><label for="name">Display in homepage: </label><input type="checkbox" name="frontPage" id="frontPage" style="width:20px;" /></div>
		<input type="hidden" name="orgId" value="<?= $this->orgId ?>" />
        <div class="datepicker">
            <label for="datetag">
                Date: 
            </label>
            <input name="datepicker_input" id="datepicker_input" />
            <input name="datetag" id="datetag" type="hidden"/>
        </div>
        <div><label for="start">Start Time</label>
        		<select name="stimeh" id="stimeh">
        			<?php echo hours(); ?>
        		</select> : 
        		<select name="stimem" id="stimem">
        			<?php echo minutes(); ?>
        		</select>
        		 <div>
        		 </div>
        		<label for="end">End Time</label>
        		<select name="etimeh" id="etimeh">
        			<?php echo hours(); ?>
        		</select> : 
        		<select name="etimem" id="etimem">
        			<?php echo minutes(); ?>
        		</select>
        		
        		</div>
		<div><label for="name">Name: </label><input type="text" name="name" id="cename" /></div>
		<div><label for="location">Location: </label><input type="text" name="location" id="celocation" /></div>
		<div><label for="description">Description: </label><textarea name="description" id="cedescription" ></textarea></div>
		<input type="hidden" id="ceid" name="ceid" value="" />
		&nbsp;<input type="submit" class="submit" value="create Event"/>&nbsp;<input type="submit" class="submit" onclick="Form.reset('addEvent');return false;" value="clear"/>
	</form>
</div>
</div>

<?php 
function hours() {
	$i = 0;
	$str = '';
	while($i<24) {
		$k = ($i < 10 ) ? '0'.$i : $i;
		$str .= "<option value='{$k}'>{$k}</option>";
		$i++;
	}
	return $str;
}

function minutes() {
	$i = 0;
	$str = '';
	while($i<60) {
		$k = ($i < 10 ) ? '0'.$i : $i;
		$str .= "<option value='{$k}'>{$k}</option>";
		$i++;
	}
	return $str;
}
