<?php
$optionOrder = array('menu', 'services', 'products', 'realestate', 'coupons', 'media', 'events', 'reviews', 'forum', 'directions', 'contact', 'banners');
$nonoptopns = array();
$nonoptopns[3] = array('realestate', 'photogallery', 'menu', 'coupons');
$nonoptopns[2] = array('photogallery', 'forum');
$nonoptopns[4] = array('realestate', 'products', 'reviews', 'photogallery', 'menu', 'coupons', 'banners', 'services');
?>
<div class="toggle ">
    Tabs <a onclick='FM.Account.showhelp(this, "TABS", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<?php $config = array();
$config = sortArrayByArray($this->config['tabs'], $optionOrder);
$this->config['tabs'] = $config;
?>
<div id="commonFeatures" class="module">
<?php //print_r($this->config);exit; ?>
	<?php foreach($this->config as $key=>$values) {
		if($key == 'tabs') {?>
		<div class="subgroup">
			<h3><?php echo $key; ?></h3>
			<?php foreach($values as $column=>$status) {
					if(in_array($column, array('id', 'orgId'))){continue;} if(!in_array($column, $nonoptopns[$this->type])) {?>
					<div class="featureWrap"><div class="feature" style="margin-left:.5em;"><input type="checkbox" class="commoncbx" id="<?php echo $key; ?>" name="<?php echo $column; ?>" <?php if($status == 1){ echo ' CHECKED '; } ?> onclick="FM.AdminWidget.CommonFeatures.doEdit(this);"/><?php echo ($column == 'media') ? 'photos' : $column; ?></div></div>
			<?php }}?>
		</div>
	<?php }} ?>
</div>

<?php
function sortArrayByArray($array,$orderArray) {
	$ordered = array();
	foreach($orderArray as $key) {
		if(array_key_exists($key,$array)) {
			$ordered[$key] = $array[$key];
			unset($array[$key]);
		}
	}
	return $ordered + $array;
}

?>