<div id="banners_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Create A Banner <a onclick='FM.Account.showhelp(this, "BANNERS", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="createBanners" class="module noimage">
	<h2 style="text-align:right;padding-bottom:.5em;">15 Banner Maximum</h2>
	<div class="clear">&nbsp;</div>
	<div>
		<div id="bannerTemplates">
			<?php
				foreach ($this->templates  as $template) { ?>
					<div class="bannerTemplateOption">
						<input type="radio" name="template" value="<?php echo $template->getId() ?>" class="bannertemplateradio" onclick="FM.BannerWidget.setSelected(this)">
						<img src="/media/image/banner_templates/<?php echo $template->getImage(); ?>" title="<?php echo $template->getName(); ?>" width="175" height="75"/>
					</div>
			<?php	} ?>
		</div>
	</div>
	<div id="createBannerFormWrapper">
		<?php //echo $this->form; ?>		
		<form class="zend_form">
		    
    		<div id=""><label>Name : </label><input type="text" name="bannername" id="bannername" value="" /></div>
    		<div id=""><label>Alt : </label><input type="text" name="banneralt" id="banneralt" value="" /></div>
    		<div id=""><label>URL : </label><input type="text" name="bannerurl" id="bannerurl" value="" /></div>
    		<div id="bannerHeadlineWrap"><label>Headline : </label><input type="text" name="bannerheadline" id="bannerheadline" value="" /></div>
    		<div id=""><label>Copy : </label><textarea name="bannercopy" value="" id="bannercopy" rows = "4"></textarea></div>
			<div class="upload_preview"><label>Image : </label><div></div></div>
            
             <div id="bannerimage" class="upload_image">
                <img src="/images/icons/upload.jpg" alt="60x60"/>
            </div>
            
            <span class="upload_btn">click to upload<b></b></span>
            
            <div id="bannerlogo" class="upload_area">
                <div id="spanSWFUploadButtonBanner">
                </div>
            </div>   
			<input type="hidden" id="bannerMediaId" name="bannerMediaId" value='' />
            <div id=""><input name="" id="" class="submit" value="clear" type="submit" onclick="FM.BannerWidget.clear(); return false;" ><input name="create" id="create" class="submit" value="create banner" type="submit" onclick="FM.BannerWidget.create(); return false;" ></div>
            
		</form>
	</div>	
</div>
</div>