<div class="toggle">
    Previous Emails <a onclick='FM.Account.showhelp(this, "PREVEMAIL", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>

</div>
<div id="previousEmailAdmin" class="module">
    <div>
    	<?php foreach ($this->emails as $key=>$email) { ?>
    		<div style="border:1px solid grey;" id="email_head_<?php echo $email->getId(); ?>">
				<div style="display:block;background-color:black;color:white;border-bottom:1px solid white;padding:4px;"><img style="cursor:pointer" src="/images/icons/open.png" onclick="FM.Account.toggleEmail(this, 'email_<?php echo $email->getid() ; ?>')" />&nbsp;<?php echo $email->getSubject() ; ?>&nbsp;<div style="width:150px;float:right;text-align:right;" ><?php echo date('m-d-Y H:i:s', strtotime($email->getDate())); ?>&nbsp;<img style="cursor:pointer" src="/images/icons/remove.png"  onclick="FM.Account.deleteSportsEmail('<?php echo $email->getid() ; ?>')"></div></div>
				<div id="email_<?php echo $email->getid() ; ?>" style="display:none;padding:5px;">
					<div>Subject : <?php echo $email->getSubject() ; ?></div>
					<div>Message :<?php echo $email->getContent() ; ?> </div>
				</div>
			</div>
    	<?php } ?>
    </div>
</div>
