<div id="coupons_wr" style="display:<?php echo $this->display; ?>">
	<div class="toggle">Manage Coupons <a onclick='FM.Account.showhelp(this, "MANAGECOUPON", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a></div>
	<div id="manageCoupons" class="module">
		<div>
			<table width="100%" id="managecoupontable" cellpadding="0" cellspacing="0" border="1">
				<tr id="managecouponheaders">
					<th>id</th>
					<th align="left">code</th>
					<!--<th>created</td>-->
					<th>active</th>
					<th>b2b</th>
					<th>view</th>
					<th>edit</th>
					<th>delete</th>
				</tr>
				<?php
	                $count = 0;
					foreach ($this->coupons as $coupon) {
	                    $count++; 
	                    ?>
						<tr id="managecoupons_<?php echo $coupon->getId() ?>" class="<?php if($count%2) { echo 'odd'; }?>">
							<td align="center"><?php echo $coupon->getId() ?></td>
							<td><?php echo $coupon->getCode() ?></td>
						<!--<td align="center"><?php echo ($coupon->isCreated()) ? 'Y' : 'N'; ?></td>-->
							<td align="center"><input onclick = "FM.CouponWidget.toggleActive(this, <?php echo $coupon->getId() ?>)" type="checkbox" name="" <?php echo ($coupon->isActive()) ? 'CHECKED' : '' ?>  /></td>
							<td align="center"><input onclick = "FM.CouponWidget.toggleB2b(this, <?php echo $coupon->getId() ?>)" type="checkbox" name="" <?php echo ($coupon->isB2b()) ? 'CHECKED' : '' ?>  /></td>
	                        <td align="center">
	                            <a class="manage_coupon" href="/couponpreview/<?php echo $coupon->getId() ?>">
	                                <img src="/images/icons/preview.png" />
	                            </a>
	                        </td>
	                          <td align="center">
                            <a onclick = "FM.CouponWidget.edit(<?php echo $coupon->getId() ?>)"  title="<?php echo $coupon->getCode() ?>">
                                <img src="/images/icons/edit.png" />
                            </a>
                        </td>
	                        <td align="center">
	                            <a  href="#" class="delete_coupon_<?php echo $coupon->getId() ?>">
	                                <img src="/images/icons/remove.png" />
	                            </a>
	                        </td>
						</tr>
				<?php } ?>
			</table>
	        <script type="text/javascript">
	            FM.CouponWidget.init();
	        </script>
		</div>
	</div>
</div>