<div id="banners_wr2" style="display:<?php echo $this->display; ?>">
<div class="toggle">Manage Banners <a onclick='FM.Account.showhelp(this, "MANAGEBANNERS", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a></div>
<div id="manageBanners" class="module">
	<div>
		<table width="100%" id="managebannertable" cellpadding="0" cellspacing="0" border="1">
			<tr id="managebannerheaders">
				<th>id</th>
				<th align="left">name</th>
				<!--<th>created</th>-->
				<th>active</th>
				<th>view</th>
				<th>edit</th>
				<th>delete</th>
			</tr>
			<?php            
                $count = 0;
				foreach ($this->banners as $banner) { 
                    $count++; 
                    ?>
					<tr id="managebanners_<?php echo $banner->getId() ?>" class="<?php if($count%2) { echo 'odd'; }?>">
						<td><?php echo $banner->getId() ?></td>
						<td><?php echo $banner->getName() ?></td>
						<!--<td align="center"><?php echo ($banner->isCreated()) ? 'Y' : 'N'; ?></td>-->
						<td align="center"><input type="checkbox" onclick = "FM.BannerWidget.toggleActive(this, <?php echo $banner->getId() ?>)" name="" <?php echo ($banner->isActive()) ? 'CHECKED' : '' ?>   /></td>
                        <td align="center">
                            <a href="/bannerpreview/<?php echo $banner->getId()?>" class="manager_banner" title="<?php echo $banner->getName() ?>">
                                <img src="/images/icons/preview.png" />
                            </a>
                        </td>
                          <td align="center">
                            <a onclick = "FM.BannerWidget.edit(<?php echo $banner->getId() ?>)"  title="<?php echo $banner->getName() ?>">
                                <img src="/images/icons/edit.png" />
                            </a>
                        </td>
                        <td align="center">
                            <a href="#" class="delete_banner_<?php echo $banner->getId() ?>">
                                <img src="/images/icons/remove.png" />
                            </a>
                        </td>
					</tr>
			<?php } ?>
		</table>
        <script type="text/javascript">
            FM.BannerWidget.init();
        </script>
	</div>
</div>
</div>