<div id="menu_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Edit Menu <a onclick='FM.Account.showhelp(this, "EDITMENU", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="menuAdmin" class="module">
	<textarea class="mceEditor" id="menu"><?php echo $this->profile; ?></textarea>
	<div>
        <input type="submit" class="submit" onclick="FM.MenuEdit.update(tinyMCE.get('menu').getContent() ,  <?php echo $this->orgId?>)" value = "update" />
    </div>
    <div>
    
    </div>	
</div>
</div>
