<div class="toggle">
    Your Information <a onclick='FM.Account.showhelp(this, "YOURINFORMATION", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="orgdataAdmin" class="module">
	<div >
		<form class="zend_form">
		<div><label>Name :</label><input type ="text" name="name"  id ="updateName" value ="<?php echo $this->orgdata->getName();?>" /></div>
		<div><label>Address 1 :</label><input type ="text" name="address1" id ="updateAddress1" value ="<?php echo $this->orgdata->getAddress1();?>" /></div>
		<div><label>Address 2 :</label><input type ="text" name="address2" id ="updateAddress2" value ="<?php echo $this->orgdata->getAddress2();?>" /></div>
		<div><label>City :</label><input type ="text" name="city" id ="updateCity" value ="<?php echo $this->orgdata->getCity();?>" /></div>
		<div><label>State :</label>
		<select name="state" id ="updateState" >
	<option value="AL">AL</option>
	<option value="AK">AK</option>
	<option value="AZ">AZ</option>
	<option value="AR">AR</option>
	<option value="CA">CA</option>
	<option value="CO">CO</option>
	<option value="CT">CT</option>
	<option value="DE">DE</option>
	<option value="DC">DC</option>
	<option value="FL">FL</option>
	<option value="GA">GA</option>
	<option value="HI">HI</option>
	<option value="ID">ID</option>
	<option value="IL">IL</option>
	<option value="IN">IN</option>
	<option value="IA">IA</option>
	<option value="KS">KS</option>
	<option value="KY">KY</option>
	<option value="LA">LA</option>
	<option value="ME">ME</option>
	<option value="MD">MD</option>
	<option value="MA">MA</option>
	<option value="MI">MI</option>
	<option value="MN">MN</option>
	<option value="MS">MS</option>
	<option value="MO">MO</option>
	<option value="MT">MT</option>
	<option value="NE">NE</option>
	<option value="NV">NV</option>
	<option value="NH">NH</option>
	<option value="NJ">NJ</option>
	<option value="NM">NM</option>
	<option value="NY">NY</option>
	<option value="NC">NC</option>
	<option value="ND">ND</option>
	<option value="OH">OH</option>
	<option value="OK">OK</option>
	<option value="OR">OR</option>
	<option value="PA">PA</option>
	<option value="RI">RI</option>
	<option value="SC">SC</option>
	<option value="SD">SD</option>
	<option value="TN">TN</option>
	<option value="TX">TX</option>
	<option value="UT">UT</option>
	<option value="VT">VT</option>
	<option value="VA">VA</option>
	<option value="WA">WA</option>
	<option value="WV">WV</option>
	<option value="WI">WI</option>
	<option value="WY">WY</option>
</select>
</div>
		<div><label>Zip :</label><input type ="text" name="zip" id ="updateZip" value ="<?php echo $this->orgdata->getZip();?>" /></div>
		<div><label>Phone :</label><input type ="text" name="phone" id ="updatePhone" value ="<?php echo $this->orgdata->getPhone();?>" /></div>
		<div><label>Email :</label><input type ="text" name="email" id ="updateEmail" value ="<?php echo $this->orgdata->getEmail();?>" /></div>
		<div><label>Website :</label><input type ="text" name="email" id ="updateWebsite" value ="<?php echo $this->orgdata->getWebsite();?>" /></div>
		<div><label style="width:230px;">Direct Link : www.4Monmouth.com/client/</label><input type ="text" name="slug" id ="updateSlug" value ="<?php echo $this->orgdata->getSlug();?>" onblur="FM.OrgDataEdit.checkSlug(this, '<?php echo $this->orgdata->getSlug();?>')" /></div>
		<div><input type="submit" class="submit" value="update" id ="update" onclick="FM.OrgDataEdit.update();return false;" /></div>
		</form>
	</div>
</div>

<script>
 $('updateState').childElements().each(
 	function(el){
 		if(el.value == '<?php echo $this->orgdata->getState();?>') {
 			el.selected = true;
 		}
 	}
 	)
</script>