<div id="products_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">Product List <a onclick='FM.Account.showhelp(this, "PRODUCTLIST", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a></div>
<div id="productlistAdmin" class="module">
    <h3>Add a product to list 
    <!--
        <div class="usetab">
            <input type="checkbox"/>Use Product List Tab
        </div>
        -->
    </h3>
	<form class="zend_form">
		<div>
	    	<div><label>Name :</label><input type ="text" name="productName"  id ="productName" value ="" /></div>
	    	<div><label>Link :</label><input type ="text" name="productLink" id ="productLink" value ="" /></div>
	    	
			
			<div class="upload_preview"><label>Image : </label><div></div></div>
	    	
	        <div id="productimage" class="upload_image">
	            <img src="/images/icons/upload.jpg" alt="60x60"/>
	        </div>
	        
	        <span class="upload_btn">click to upload<b>60x60</b></span>
	        
	        <div id="productswf" class="upload_area">
	            <div id="swfUploadProduct"></div>
	        </div>    
        </div>
        <div style="clear:both;margin-top:3.5em;overflow:hidden;">Description :<textarea name="productDesc" id ="productDesc" value ="" class="mceEditor" ></textarea>
    	<input type="hidden" id="productimagename" value="" />
    	<input type="submit" class="submit" value="Add Product" onclick="FM.ProductList.createProduct();return false;" />
		</div>
	</form>
       
</div>

</div>