<div class="toggle">
    Edit Profile <a onclick='FM.Account.showhelp(this, "PROFILE", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="profileAdmin" class="module">
	<textarea class="mceEditor" id="description"><?php echo $this->profile; ?></textarea>
	<div>
        <input type="submit" class="submit" onclick="FM.ProfileEdit.update(tinyMCE.get('description').getContent() , <?php echo $this->orgType ?>)" value = "update" />
    </div>
    <div>
        <script type="text/javascript">
        tinyMCE.init({
            // General options
            width: "525px",
            height:"500px",
            mode : "textareas",
            theme : "advanced",
            editor_selector : "mceEditor",
            plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,imagemanager,filemanager",
        
            // Theme options
            theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect,fullscreen,code,preview,help",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,bullist,|,link,unlink,backcolor,tablecontrols,|,hr,nonbreaking",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : false,
        
            // Example content CSS (should be your site CSS)
            content_css : "css/example.css",
        
            // Drop lists for link/image/media/template dialogs
            template_external_list_url : "js/template_list.js",
            external_link_list_url : "js/link_list.js",
            external_image_list_url : "js/image_list.js",
            media_external_list_url : "js/media_list.js",
        
            // Replace values for the template plugin
            template_replace_values : {
                username : "Some User",
                staffid : "991234"
            }
        });
        </script>
    </div>	
</div>
