<div class="toggle">
    Password Protection
</div>
<div id="pwdprotect" class="module">
    <div>
    	<div><input type="checkbox" id="pdpro" onclick="FM.Account.toggleSportsProtected(this)"  <?php print ($this->sport->isProtected()) ? ' CHECKED ' : '' ;?> />&nbsp;<label>Enable Protection</label></div>
    	<div style="margin:1em;"><i>When checked users will have to sign in before they can view any information.</i></div>
    </div>
</div>