<div id="realestate_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Real Estate  List <a onclick='FM.Account.showhelp(this, "RELISTINGS", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="realestatelistAdmin" class="module" style="margin:0px;">
    <h3>Add a real estate listing
    <!--
        <div class="usetab">
            <input type="checkbox" />Use Real Estate List Tab
        </div>
        -->
    </h3>
	<form class="zend_form">
		<div><label>Id <i>(ex listing id)</i> :</label><input type ="text" name="realestateName"  id ="realestateName" value ="" /></div>
		<div><label>Link :</label><input type ="text" name="realestateLink" id ="realestateLink" value ="" /></div>
		<div><label>Address :</label><input type ="text" name="realestateAddress" id ="realestateAddress" value ="" /></div>
		<div><label>City :</label><input type ="text" name="realestateCity" id ="realestateCity" value ="" /></div>
		<div><label>State :</label><input type ="text" name="realestateState" id ="realestateState" value ="" /></div>
		<div><label>Zip :</label><input type ="text" name="realestateZip" id ="realestateZip" value ="" /></div>
		<div><label>Decsription :</label><textarea name="realestateDesc" id ="realestateDesc" value =""></textarea></div>
        <div class="upload_preview"><label>Image : </label><div></div></div>
		
        <div id="realestateimage" class="upload_image">
            <img src="/images/icons/upload.jpg" alt="60x60"/>
        </div>
        
        <span class="upload_btn" style="text-align:center">click to upload<b>150x100</b><i>max</i></span>
		
        <div id="realestateswf" class="upload_area">
            <div id="swfUploadListing">
            </div>
        </div>        
        
		<input type="hidden" id="realestateimagename" value="" />
		
		<input type="submit" class="submit" value="add listing" onclick="FM.RealEstateList.createListing();return false;" />
		
	</form>
</div>
<div class="clear">&nbsp;</div>
</div>