<div id="services_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Edit Services <a onclick='FM.Account.showhelp(this, "EDITSERVICES", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="servicesAdmin" class="module" style="margin:0px;">
<form class="zend_form">
	<textarea class="mceEditor" id="services"><?php echo $this->profile; ?></textarea>
	<div>
        <input type="submit" class="submit" onclick="FM.ServicesEdit.update(tinyMCE.get('services').getContent() , <?php echo $this->orgId?>);return false;" value = "update" />
    </div>
   </form>
    <div>
   
    </div>	
</div>
</div>
