<div id="menu_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Edit Your Schedule
</div>
<div id="sportsscheduleAdmin" class="module">
	<textarea class="mceEditor" id="sportsschedule" value="<?php echo $this->profile; ?>"><?php echo $this->profile; ?></textarea>
	<div>
        <input type="submit" class="submit" onclick="FM.SportsScheduleEdit.update(tinyMCE.get('sportsschedule').getContent() ,  <?php echo $this->orgId?>)" value = "update" />
    </div>
    <div>
    
    </div>	
</div>
</div>
