<div id="reviews_wr" style="display:<?php echo $this->display; ?>">
<div class="toggle">
    Manage Reviews <a onclick='FM.Account.showhelp(this, "REVIEWS", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="manageTestimonials" class="module">
		<h3>Add Review</h3>
		<form class="zend_form" id="addTestimonialForm" onsubmit = "FM.AdminWidget.Testimonials.add();return false;">
			<div><label>Courtesy of:</label><input type="text" id="reviewername" name="reviewername" value = '' /></div>
			<div><label>Email :</label><input type="text" id="from" name="from" value = '' /></div>
			<div><label>Testimonial:</label><textarea id="testimonialInput" name="testimonial" rows="6"></textarea></div>
			<!--<input type="hidden" name="orgId" id="orgId" value="<?php echo $this->orgId ?>" />-->
			<input type = "submit" class="submit" value = "Add Testimonial" />
		</form>
		
        <?php
        if($this->testimonials){?>        
    		<h3>Manage Reviews</h3>
    		<div id="reviewScroll">
    		<p><i>Roll over review short to view in entirety</i></p>
    		<?php
    		foreach($this->testimonials as $index=>$test) { ?>
    		<div id="del_<?php echo $test['id']; ?>" >      
    			<div class="question" style="border-bottom:1px solid black;" onmouseover="$('a<?php echo $index; ?>').style.display = 'block'" onmouseout="$('a<?php echo $index; ?>').style.display = 'none'">
    				<span><a name="f<?php echo $index; ?>"><?php echo substr($test['testimonial'], 0, 100); ?>...</a>
    				<div style="width:100px;float:right;text-align:right;"><label><a> Active </a></label><input type="checkbox" name="" value="" onclick="FM.AdminWidget.Testimonials.toggleActive(this, <?php echo $test['id']; ?>)" <?php if($test['active']){print ' CHECKED ';} ?>/>
    			       <a href="#" id="faq_<?php echo $test['id'];?>" class="edit" onclick = "FM.AdminWidget.Testimonials.populateedit(this);return false;" ><img src="/images/icons/edit.png" /></a>
               			 <a href="#" id="d_<?php echo $test['id'];?>" class="delete" onclick = "FM.AdminWidget.Testimonials.deleteTestimonial(<?php echo $test['id']; ?>);return false;" ><img src="/images/icons/remove.png" /></a>
               			 </div>
               			 <div class="clear">&nbsp;</div>
    			</div>
    			
                <div class="answer" id="a<?php echo $index; ?>" style="display:none"><?php echo $test['testimonial']; ?></div>
                <div class="clear">&nbsp;</div>
    		</div>
    		<?php }?>
    		</div>
        <?php
        }
        ?>
</div>
</div>