<div class="toggle">
   Email Blast Message "EBM"   200 characters max <a onclick='FM.Account.showhelp(this, "EBM", event)'><img src="/images/icons/question_icon.gif" height="15" width="15" /></a>
</div>
<div id="textAdAdmin" class="module" style="margin:0px;">
<form class="zend_form">
	<textarea class="mceEditor" id="textad"></textarea>
	<div>
        <input type="submit" id="submit" class="submit" onclick="FM.TextAd.insert(tinyMCE.get('textad').getContent() , <?php echo $this->orgId?>);return false;" value = "submit" />
         <input type="submit" id="submit" class="submit" onclick="FM.TextAd.clear();return false;" value = "clear" />
        <input type="hidden" id="textAdId" value=''>
    </div>
   </form>
    <div>
   <script>
  // FM.onDomReady(function()
  // { alert(tinyMCE.get('textad').getContent());
  // });
  // function myHandleEvent(e) {
  // 	alert("event:" + e.type);
  // 	return true; // Continue handling
  // }

   </script>
    </div>	
</div>
