<div >
<?php echo $this->layout()->weather; ?>
	<div style="text-align:right;margin:0 0 .3em;padding-top:0px;background:#DCE81C;"><a href="/limecard"><img src="/images/home/limecard.jpg" /></a></div>
    
    <?php echo $this->layout()->featuredOrganization; ?>
    <?php echo $this->layout()->astrology; ?>
    <?php echo $this->layout()->rod; ?>
    <?php echo $this->layout()->spotlight; ?>
</div>
