<div class="tab_content" id="<?php echo $this->id ?>">
<h6>Admin Panel</h6>
    <div class="utils">
		 <img class="reload" title="reload" src="/images/icons/reload.png" onclick="window.location.reload()"/>
        <img class="collapse" title="collapse" src="/images/icons/collapse.png"/><img class="explode" title="expand" src="/images/icons/explode.png"/>
    </div>
	<?php echo $this->profile ?>    
    <div class="utils">
		 <img class="reload" title="reload" src="/images/icons/reload.png" onclick="window.location.reload()"/>
        <img class="collapse" title="collapse" src="/images/icons/collapse.png"/><img class="explode" title="expand" src="/images/icons/explode.png"/>
    </div>
</div>