<div style="width:100%;">
<div style="width:200px;float:left;">
<a onclick="FM.Events.getNext(<?php echo $this->previousMonth; ?>, <?php echo $this->previousYear; ?>)"><img src="/images/icons/previous.png" />&nbsp;<?php echo date('M, Y', strtotime($this->previousYear . '-' . $this->previousMonth . '-01')); ?></a>
</div>
<div style="width:200px;float:right;text-align:right;">
<a onclick="FM.Events.getNext(<?php echo $this->nextMonth; ?>, <?php echo $this->nextYear; ?>)"><?php echo date('M, Y', strtotime($this->nextYear . '-' . $this->nextMonth . '-01')); ?>&nbsp;<img src="/images/icons/next.png" /></a>
</div>
</div>
<!--
	<h6>Upcoming Events!</h6>
	
	<?php foreach ($this->events as $datetag=>$day) { $date = date('l - F j, Y', strtotime($datetag)); ?>
	
		<h4><?= strtoupper($date) ?></h4>
	
		<?php foreach ($day->getEvents() as $event) { ?>
	
		<div class="calendar_event">
			<strong><?= $event['name'] ?></strong><br />
			<strong>Location: </strong><?= $event['location'] ?><br />
			<strong>Description:</strong>
			<?= $event['description'] ?>
			<br /><br />
		</div>
		
	<?php }?>

	<hr />

	<?php } ?>
	-->
<?php print $this->obj->__toString(); ?>	
