<div class="tab_content" id="<?php echo $this->id ?>">
    <h6>Directions</h6>
    
    <div id="gmap">
        <form class="zend_form" >
            <label>from:</label>
            <input class="direction_from" name="direction_from" id="direction_from" type="text"/>
            <input type="submit" id="submit"value="get directions"/>
            <input name="direction_to" id="direction_to"  type="hidden" type="text" value="<?php echo $this->address['address1'].', '.$this->address['city'].', NJ';?>"/> 
        </form>
        <div id="map_canvas"></div>
    </div>
    <div id="directionsPanel"></div>
    <script type="text/javascript" src='/js/tabs/directions.js'></script>
    <script type="text/javascript">
        jQuery(function(){
            FM.Directions.init();
        })
    </script>
</div>
