<div class="tab_content" id="<?php echo $this->id ?>">
	<h6>Our Forum</h6>
	<div id="contactForm">
		<?php echo $this->profile ?>
	</div>
	<div class="clear">&nbsp;</div>
	<div id="messages">
		<?php
	foreach ($this->items as $index=>$obj) {
		$delete = '';
		if($this->admin){$delete = '<a onclick="FM.Forum.deleteComment('. $obj->getId() . ')"><img src="/images/icons/remove.png" /></a>';}
?>
	<div class="forumWrap" id="forumItem_<?php echo $obj->getId(); ?>">
		<div class="forumNameDate"><div class="name"><?php echo $obj->getName(); ?></div><div class="date"><?php echo $obj->getTime(); ?> <?php echo $delete; ?></div></div>
		<div class="forumMessage"><?php echo $obj->getMessage(); ?></div>
	</div>
<?php
	}
?>
	</div>
</div>