<div id="tabGroup">
	<?foreach ($this->tabs as $t) {?>
		<div class="tab<? if($t['selected']) { print " selected"; } ?>" id="t_<?php print $t['id']; ?>">
	    	<a id="tab_<?php print $t['id']; ?>" ><?php print $t['label']; ?></a>
	  	</div>
	<?}?>
	</div>
	<div id="content">
		<?foreach ($this->tabs as $tab) {
			//if($tab['selected']) {
					print $tab['tab']->toHTML($tab['id']);
			//	}
	}?>
</div>