<div id="clients" class="mod">
<h4>Current Category : <span><?print ucwords(strtolower($this->catname));?></span> </h4>
<?php $clientCount = (is_array($this->clients) && count($this->clients));
	$start = ($clientCount) ? '1' : '0';$high = (count($this->clients) > 25) ? '25' : count($this->clients); ?>
	<div class="pagination" style="position:relative;" >Results: <span id="resultCount" ><?php echo $start;?> - <?php echo $high;  ?></span> of <span class="total"><?php echo count($this->clients); ?></span>
      <span class="pages" style="text-align:right;width:575px;float:right;position:absolute;top:0px;right:2px;">
             <?php $pages = ceil(count($this->clients) / 25);
             $i = 0;
             $totalClients = count($this->clients);
             if($totalClients  > 25) {
             	echo 'pages : ';
             	while($i < $pages) {
             		$selected = ($i == 0) ? ' class="selected" ' : '';
             		$page = $i + 1;
             		echo '<a href="#"'.$selected.'>'.$page.'</a> ';
             		$i++;
             	}
             }
         	?>
        </span>
    </div>
    <div style="clear:both;">&nbsp;</div>
		<div class="lists">		
                <?php
                $i = 0;
                $j = 0;
                $k = 0;
                if(!$clientCount) {
                	echo "There are no clients in this category.";
                }
                else{
                foreach($this->clients as $index=>$client) {?>
                <?php if($i == 0 && $j > 0) { ?>
                <table class="listing unactive" id="result_<?php echo $j; ?>">
					<tbody>
						<tr>
							<th>Id</th>
							<th class="name">Name</th>
							<th>Hits</th>
							<th class="email"> Email</th>
							<th> Active</th>
							<th> Edit</th>
							<th>Delete</th>
						</tr>
                <?php } elseif($i == 0 && $j == 0) {  ?>
                <table class="listing" id="result_<?php echo $j; ?>">
				<tbody>
					<tr>
						<th>Id</th>
						<th class="name">Name</th>
						<th>Hits</th>
						<th class="email"> Email</th>
						<th> Active</th>
						<th> Edit</th>
						<th>Delete</th>
					</tr>
	                <?php } ?>			
					<?php
					//foreach($this->clients as $index=>$client) {?>
					<?php //print_r($client->getCategoryNames()); ?>
					<tr class="<?php echo ($i % 2 == 1) ? 'odd' : '' ?>">
						<td class="id"> <?php echo $client['id']; ?></td>
						<td class="name"><a href="/sports/<?php echo $client['id']; ?>" target="_blank"><?php echo stripslashes($client['name']); ?></a></td>
						<td class="hits"> <?php echo ($client['count'] != '') ? $client['count'] : '0' ; ?></td>						
						<td class="email"> <?php echo $client['email']; ?></td>
						<td class="active"> <input type="checkbox" id="cbx_<?php echo $client['id']; ?>" <?php if($client['active'] == 1){echo ' CHECKED '; } ?> onclick="FM.BusinessClient.toggleActive(this)"></input></td>
						<td class="edit">
							<img id="edit_<?php echo $client['id'];?>" src="/images/icons/edit.png">
						</td>
						<td class="delete">
							<img id="delete_<?php echo $client['id']; ?>" title="<?php echo stripslashes($client['name']); ?>" src="/images/icons/remove.png" alt="add" height="16" width="16">
						</td>
					</tr>			
					 <?php $i++;
					 $k++;
					 if($i == 25 || $k == $totalClients) {
						?>
        		</tbody>
			</table>
                <?php } 
                if($i == 25){
                	$i = 0;
                	$j++;
                }
           } }?>
	</div>
</div>